Feature : Ajout de posthog + maintien de matomo
betagouv/mission-transition-ecologique pull request #1016
Opened 2024-08-27 12:47 UTC by oumeimaelisbihani

- ajout de posthog pour capturer les événements
- maintien de matomo
- css composant gestionnaire de cookies (tarte au citron)

2024-09-09 09:43 UTC, ttdm reviewed
Praise, gros travail ! très propre. 
J'ai juste quelques petits points avant d'approve.

2024-09-09 09:43 UTC, ttdm commented on apps/web/src/components/TeeFooter.vue
> +          </li>
Suggestion: Modifier le style pour qu'il soit identique au style des autres liens du footer. 
Pas obligatoire car lien vs popup.

2024-09-09 09:43 UTC, ttdm commented on apps/web/src/utils/matomo.ts
> +      _paq.push(['disableCookies']);
praise

2024-09-09 09:43 UTC, ttdm commented on apps/web/src/utils/analytics.ts
> +  }
Question: Il manque pas le call matomo ?

2024-09-09 09:43 UTC, ttdm commented on apps/web/src/main.ts
> +  }
Suggestion: créer méthode capturePageView dans Analytics et y déplacer ces quelques lignes. 

Question: je pense que c'est un évènement qu'il doit être possible d'envoyer quand même s'il y a un refus du cookie posthog. Par contre l'envoi doit être anonyme mais je me demande si ça n'est pas déjà géré par l'option posthog que tu as set ailleurs.

2024-09-10 15:21 UTC, oumeimaelisbihani commented on apps/web/src/main.ts
> +  }
@ttdm de ce que j'ai lu avec  person_profiles: 'always', on aura toujours un id généré. Du coup je sais pas si ça se fait d'envoyer l'event si on veut pas de cookies

2024-09-10 15:32 UTC, oumeimaelisbihani commented on apps/web/src/components/TeeFooter.vue
> +          </li>
@ttdm j'aime bien l'idée d'avoir un truc différent comme pas la même action ! à voir selon les autres retours

2024-09-16 16:52 UTC, ttdm commented on apps/web/src/utils/analytics.ts
> +  }
Je suis désolé je n'ai pas vu ta réponse ! 
Non l'idée c'est de continuer à utiliser les deux en parallèle pour avoir un suivi sur les stats générales via le dashboard de matomo et de pouvoir avoir plus de détails sur le comportement actuel des utilisateurs via posthog.

2024-09-23 13:26 UTC, yvalentin requested changes

2024-10-02 13:19 UTC, yvalentin approved these changes

2024-10-02 14:26 UTC, merged