Fix : Correction fil d'ariane
betagouv/mission-transition-ecologique pull request #1019
Opened 2024-08-27 15:32 UTC by oumeimaelisbihani

- ajout du breadcrumb dans les catalogues projets + programs
- adaptation du composant pour afficher les bons intitulés selon la route
- ajout margin bottom

2024-08-29 15:18 UTC, yvalentin requested changes
Quelques retours de demande de modif

praise: dans l'ensemble super propre

2024-08-29 15:18 UTC, yvalentin commented on apps/web/src/components/element/TeeDsfrBreadcrumb.vue
>      return 'Vos résultats'
suggestion: petit simplification possible

```ts
if (navigationStore.isCatalog) {
    return 'Liste des ' + (navigationStore.isCatalogAboutPrograms ? 'dispositifs' : 'projets')
  } else {
    return 'Vos résultats'
  }
```

2024-08-29 15:18 UTC, yvalentin commented on apps/web/src/components/element/TeeDsfrBreadcrumb.vue
> +const allBreadcrumbs = computed(() => {
suggestion: simplification du nom de variable `breadcrumbs`

2024-08-29 15:18 UTC, yvalentin commented on apps/web/src/components/objective/ThemeSelect.vue
> +  useNavigationStore().hasSpinner = false
question: pourquoi avoir modifié cette partie (ça semble en dehors du scope du fix ?

2024-08-29 15:18 UTC, yvalentin commented on apps/web/src/pages/TeeAccessibilityPage.vue
> +        :links="[{ text: 'Accessibilité', to: '/accessibilite' }]"
todo: le format avec les routeName doit être utilisé

```ts
{ name: RouteName.Accessibility }

2024-08-29 15:18 UTC, yvalentin commented on apps/web/src/pages/TeeLegalPage.vue
> +        :links="[{ text: 'Mentions légales', to: '/mentions-legales' }]"
todo: le format avec les routeName doit être utilisé, idem pour les autres...

s'il manque des entrées dans routeName, est-ce que tu peux l'ajouter ? Et modifier le code en relation

2024-08-29 15:18 UTC, yvalentin commented on apps/web/src/types/routeType.ts
> +  Statistiques = 'statistics',
typo: `Statistiques = 'statistics'` = `Statistics = 'statistics',`

2024-09-02 08:59 UTC, oumeimaelisbihani commented on apps/web/src/components/objective/ThemeSelect.vue
> +  useNavigationStore().hasSpinner = false
en effet c'est le fix de la tâche #1025 , j'avais pas remarqué qu'il y avait une tache specifique >> j'ai rollback

2024-09-02 14:02 UTC, yvalentin requested changes

2024-09-04 08:27 UTC, yvalentin approved these changes

2024-09-04 08:40 UTC, merged