Feat: Titres spéciaux pour mobiles dans les onglets résultat du parcours "je n'ai pas de projet en tete"
betagouv/mission-transition-ecologique pull request #1043
Opened 2024-09-03 08:25 UTC by oumeimaelisbihani

- refactor css
- ajout de la props "mobiletitles" dans Result List in tabs et utilisation dans TeeTabs

2024-09-04 07:34 UTC, ttdm approved these changes
Parise, ras. 

Attention à ne pas commit la sitemap et créer un nouveau ticket pour une problème identifié sur la sitemap générée.

2024-09-04 07:34 UTC, ttdm commented on apps/web/public/sitemap.xml
> -  <url>
Je pense qu'il faut enlever la sitemap de cette PR
...
et créer une nouvelle issue puisque visiblement "aides-entreprise" n'est plus dans la sitemap. 
Je pense savoir pourquoi. (Utilisitation d'un Enum plutôt que de la string en dur.)
En tout cas, ça peut être intéressant d'en faire une issue pour le prochaine sprint.

2024-09-04 14:03 UTC, yvalentin commented on apps/web/public/sitemap.xml
> -  <url>
Pour récupérer une route avec ça routeName

exemple
```ts
new URL(useRouter().resolve({ name: RouteName.PersonalData }).href, window.location.origin).href
```

2024-09-04 14:57 UTC, oumeimaelisbihani commented on apps/web/public/sitemap.xml
> -  <url>
c'est créé ici >> https://github.com/betagouv/mission-transition-ecologique/issues/1057

2024-09-09 09:15 UTC, yvalentin requested changes

2024-09-09 09:15 UTC, yvalentin commented on apps/web/src/components/element/TeeTabs.vue
> +  mobileTitles: () => [],
suggestion: ici, on pourrait peut être se passer de `mobileTitles` avec quelques choses du genre

```ts
export type { TeeDsfrTabs }

interface TeeDsfrTabs extends Omit<DsfrTabsProps, 'tabTitles'> {
  tabTitles?: (Omit<DsfrTabsProps['tabTitles'][number], 'title'> & { title: string | { title: string; size: string }[] })[]
}
```
note: pour les breakpoints, on part du principe que c'est du 'from'
exemple.
`sm`: à partir de small screen et au dessus.

2024-09-09 14:26 UTC, oumeimaelisbihani commented on apps/web/src/assets/scss/grid.scss
> +
@yvalentin le fr-hidden-sm c'est pour minimum 36em (575px) du coup pour les mobiles ça marche pas d'où la version xs que j'ai rajouté pour les écrans entre 0 et 575px

2024-09-11 09:31 UTC, yvalentin approved these changes
Approve après les changements discutés

2024-09-16 13:29 UTC, merged