refactor: refactor color usage across the app
betagouv/mission-transition-ecologique pull request #1045
Opened 2024-09-03 12:52 UTC by dolemoine

- Généralise l'utilisation de l'enum Color pour remplacer les valeurs hexa définies en dure.
- Nettoyage de certains styles scopés
- Ajout de nouvelles propriétés pour la gestion des couleurs sur les themes
- Suppression de certains couleurs pour conserver uniquement les couleurs de la palette définie dans le design : https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6514-275288&node-type=FRAME&t=Ax2keBHYiftFY0mR-0

close #753 & #972

2024-09-09 09:41 UTC, oumeimaelisbihani approved these changes
[praise] : ras pour moi, c'est propre!

2024-09-09 09:46 UTC, dolemoine commented on apps/web/src/assets/scss/setting/_color.scss
> -$base-yellow-light: #fef7da;
Oui, je sais que tu m'avais déjà fait cette remarque, mais ça permet d'être cohérent avec l'ordre défini dans la charte de couleur des maquettes, c'était assez pénible d'avoir un ordre différent.

2024-09-09 09:52 UTC, dolemoine commented on apps/web/src/components/catalog/element/CatalogBanner.vue
> -    :bg-color="bgColor ?? Color.blueLight"
Yes ça a été validé avec Coline, on a passé en revue toutes les petites exceptions sur l'app pour virer toutes les occurences de couleurs un peu custom qui ne seraient pas issues de la charte définie.

2024-09-09 09:58 UTC, dolemoine commented on apps/web/src/assets/scss/tool/_color.scss
>  }
En fait l'utilisation de lighten n'est pas recommandée, et la fonction est même exclue du modul sass par défaut d'après la doc : https://sass-lang.com/documentation/modules/color/#lighten
Par contre je peux effectivement renomer les propritété et le nom des mixin pour plus de cohérence (j'ai effectivé pas pensé à retoucher cette partie...).
On peut en parler de vive voix si besoin.

2024-09-09 10:02 UTC, dolemoine commented on apps/web/src/assets/scss/tool/_color.scss
>  }
Si on s'entend sur une solution sur le point suivant, je suis d'avis de ne conserver qu'une méthode puisque l'ancienne n'est plus utilisée par le système de gestion de nuances de couleurs

2024-09-09 12:11 UTC, ttdm commented on apps/web/src/assets/scss/tool/_color.scss
>  }
Effectivement, du coup tu peux utiliser scale comme proposé plutot que d'utiliser l'opacité ;)

2024-09-16 13:12 UTC, yvalentin requested changes
Trop cool enfin d'avoir cette harmonisation des couleurs !!

Des petits manquement peut être :
- apps/web/src/components/home/TeeCta.vue:11
- apps/web/src/components/questionnaire/TeeQuestionnaire.vue:32
- apps/web/src/components/track/detail/TrackCallout.vue:25 (headerStyle ne semble plus utilisé)
- apps/web/src/components/track/detail/TrackCallout.vue:57
- apps/web/src/components/track/form/TrackButton.vue:5
- apps/web/src/components/track/form/TrackButtonInput.vue:9

2024-09-16 13:12 UTC, yvalentin commented on apps/web/src/components/project/details/ProjectDetail.vue
> +})
suggestion: ceci semble être factorisable en déportant le computed dans une classe/fichier comme pour les `Project.filter()` (??)

2024-09-16 13:12 UTC, yvalentin commented on apps/web/src/types/theme/types.ts
> +  titleColor?: Color
note: A discuter

2024-09-16 17:11 UTC, ttdm commented on apps/web/src/components/program/detail/ProgramDetail.vue
> +            <div class="fr-col-justify--left fr-text--purple fr-h6 fr-text--bold fr-mb-5v">
Hmm, perso je vois deux possibilités: 

- déclarer une classe dans le css scoped (ou dans un fichier plus générique si l'utilisation est plus générique) et call une seule classe de styling             <div class="fr-col-justify--left fr-mb-5v styling-program-details-title">
- ajouter une div pour le styling, à l'intérieur de la div de spacing (un peu comme en design atomique ou on inclue le styling dans le spacing)

Je crois que je préfère la première version mais les deux permettent de clairement et facilement identifier ce qui correspond à du spacing ou du styling. 
(Une solution alternative serait de dire, on met toujours le styling avant le spacing dans les camps 'class' mais en pratique c'est difficile à mettre en place)

ça reste de l'ordre du détail vis à vis de la PR.

2024-09-18 15:33 UTC, dolemoine commented on apps/web/src/assets/scss/setting/_color.scss
> +$base-grey: #777;
suggestion intégrée

2024-09-23 09:19 UTC, dolemoine commented
> Trop cool enfin d'avoir cette harmonisation des couleurs !!
> 
> Des petits manquement peut être :
> 
>     * apps/web/src/components/home/TeeCta.vue:11
> 
>     * apps/web/src/components/questionnaire/TeeQuestionnaire.vue:32
> 
>     * apps/web/src/components/track/detail/TrackCallout.vue:25 (headerStyle ne semble plus utilisé)
> 
>     * apps/web/src/components/track/detail/TrackCallout.vue:57
> 
>     * apps/web/src/components/track/form/TrackButton.vue:5
> 
>     * apps/web/src/components/track/form/TrackButtonInput.vue:9

- apps/web/src/components/home/TeeCta.vue:11: done
- apps/web/src/components/questionnaire/TeeQuestionnaire.vue:32: j'ai un gros doute sur le fait que bgColor dans track soit toujours utilisé, idem pour la méthode getTrackBgColor. Je veux bien faire un rapide tour avec toi mais j'ai l'impression que c'est obsolète
- apps/web/src/components/track/detail/TrackCallout.vue:25: headerStyle supprimé
- apps/web/src/components/track/detail/TrackCallout.vue:57: le hint non plus ne semble plus utilisé ?!
- apps/web/src/components/track/form/TrackButton.vue:5: done -> contraint d'ajouter un `!important` dans le mixin du get background color
- TrackButtonInput: ce component ne semble plus être utilisé. Si tu confirmes, je le vire ?

2024-09-26 14:12 UTC, dolemoine commented
les derniers points vus ensembles ont été traités
je n'ai pas touché à la notion de hint du track callout pour le moment, vu que ça ne relève pas de la gestion de la couleur

2024-09-27 08:47 UTC, yvalentin approved these changes

2024-09-27 13:31 UTC, merged