Refactor/border styling
betagouv/mission-transition-ecologique pull request #1047
Opened 2024-09-03 14:41 UTC by dolemoine

2024-09-29 22:19 UTC, ttdm requested changes
Petite remarque pour la PR sur les couleurs (dont cette PR dépend) : j'ai vu au moins une diff de couleur très visible. Le bg bleu sur la home page passe pour moi d'une teinte de bleu à plutôt du gris. Au niveau perception ça fait une grosse différence ! . 

Sur cette PR, une fois que la PR des couleurs sera à nouveau merge, je trouve ça très cool. 
J'ai noté des petits changements de couleurs sur chacune des borders mais rien qui ne me semble problématique. 

note: j'ai mis la PR en bloquante car il faut gérer les couleurs mais RAS sur la partie border

2024-09-29 22:19 UTC, ttdm commented on apps/web/src/components/element/TeeContentBlock.vue
> +  return props.borderPosition.map((position) => `fr-border-${position}--grey--light`).join(' ')
ça fait une toute petite différence (ddd->d6d6d6) de couleur mais c'est aussi super clean ! nice ;)

2024-09-29 22:19 UTC, ttdm commented on apps/web/src/components/track/form/TrackSiret.vue
> +      :class="isSelected(i) ? 'fr-bg--grey--lightness fr-text--blue-france fr-border--blue-france' : 'fr-border--grey--light'"
idem petites diffs de couleurs mais OK pour moi.

2024-09-29 22:19 UTC, ttdm commented on apps/web/src/components/program/list/ProgramList.vue
>  }
suggestion: utiliser ton style sur ce composant pour encore plus d'uniformisation

2024-09-29 22:19 UTC, ttdm commented on apps/web/src/types/border.ts
je me demande si ce fichier est encore utile avec ta proposition de scss ?

2024-10-03 08:58 UTC, dolemoine commented on apps/web/src/types/border.ts
mmh c'est vrai que j'ai bossé sur ces classes borders en parallèle de la création de cet enum sur une autre refacto... peut être qu'il y a quelque chose à faire là dessus, je regarde

2024-10-03 08:59 UTC, dolemoine commented on apps/web/src/components/program/list/ProgramList.vue
>  }
je ne voulais pas trop toucher cette partie pour le moment car quand Oumeima a bossé sur ce composant, on a pas pu trouver une solution pour passer directement des classes génériques au composant sur un event `active`. D'où l'utilisation d'un css dans le composant qui malheureusement nous facilite pas l'utilsation des classes générique

2024-10-04 14:53 UTC, dolemoine commented on apps/web/src/types/border.ts
c'est supprimé au profit de l'utilisation des classes css

2024-10-09 08:32 UTC, yvalentin commented on apps/web/src/assets/scss/setting/_border.scss
> +);
suggestion: peut être mettre ça dans un fichier _position.scss ? Est-ce que ça pourrait être utilisé sur d'autres proprieter CSS ?

Si non, plutôt mettre  un nom de variable genre `border-position` car quand on utilise les settings `setting.$widths` peut prêter à confusion. (ceux qui semble être moins le cas pour les autres variables dans setting: $rounded, $corner,...)

2024-10-09 08:33 UTC, yvalentin commented on apps/web/src/assets/scss/setting/_border.scss
> +$styles: (
suggestion: changer `$styles` par `$border-styles` (on a déjà par exemple `font-styles`)

2024-10-09 08:33 UTC, yvalentin commented on apps/web/src/assets/scss/setting/_border.scss
> +$widths: (
suggestion: changer $widths par $border-widths

2024-10-09 09:45 UTC, dolemoine commented on apps/web/src/assets/scss/setting/_border.scss
> +);
pour le moment je ne vois pas d'autre cas d'usage, j'ajoute le prefix `border-`

2024-10-09 10:18 UTC, yvalentin approved these changes

2024-10-11 10:07 UTC, merged