Refacto : Utilisation d'un seul composant TeeForm pour le contact projet et dispositif
betagouv/mission-transition-ecologique pull request #1073
Opened 2024-09-09 10:11 UTC by oumeimaelisbihani

- Séparation du composant TeeForm en plusieurs sous composants pour plus de lisibilité 
- Slots pour les champs custom du formulaire (utilisation pour le projet)

2024-09-10 17:43 UTC, dolemoine reviewed
J'ai commencé à regarder un peu ce gros bébé, et je me demandais si on pouvait ouvrir une discussion sur l'approche.
Dans l'idée de rendre le formulaire le plus générique possible, j'aurai bien vu un composant vue qui se baserait sur un type un peu plus enrichis, dans lequel on pourrait par exemple définir le type de champ de formulaire, sa taille (pour reprendre la notion de size que tu as intégré, ou du nombre de rows dans le cadre d'un textarea).
Pourquoi pas se baser sur le TrackFIeldType (peut-être le rendre plus générique et partagé?) : 
```javascript

export enum TrackFieldType {
  Text = 'text',
  Number = 'number',
  Select = 'select',
  Radio = 'radio',
  Checkbox = 'checkbox',
  Textarea = 'textarea',
  Email = 'email',
  Tel = 'tel',
  Date = 'date',
  Search = 'search'
}
```
On pourrait utiliser un enum équivalent pour ajouter une propriété `fieldType` dans le `DefaultFieldFormType` ainsi que des propriétés pour le `size` et le `rows` : 
```javascript
type DefaultFieldFormType = {
  required: true
  isValid: boolean | undefined
  label?: string
  hint?: string
  callOut?: InputCalloutType
  fieldType: FormFieldType
  fieldColSize?: number
  fieldRowSize?: number
  ...
}
```
Du coup, dans le TeeForm, on n'est plus dépendant des champs qui sont explicites dans ton cas (un prénom, un nom, un email, etc...), mais on peut simplement itérer sur les champs qu'on passerait en props au TeeForm, pour créer les TeeFormElement dont on a besoin. Je trouve que ça rendrait le TeeForm plus générique et on déporte les spécificités de chaque formulaire dans le component parent qui intègre le TeeForm.
Ça permet aussi de s'affranchir du `slot` `customFields` puisque le côté custom serait géré du côté de la définition des champs en amont.
Ça demanderait aussi probablement d'avoir un object de type `OpportunityFormType` défini globalement, qui embarquerait par défaut les propriétés définies dans le `TeeForm`, et qu'on pourrait surcharger au besoin selon le type de formulaire à créer.
Du côté du `TeeForm` on ne conserverait donc que la création des champs selon les propriétés définies en amont dans le component parent, ainsi que la logique de vérification/validation des champs, et de soumission du formulaire.
Sur ce dernier point, ça pose aussi question. Aujourd'hui on appelle OportunityApi, mais quid d'un cas où la soumission du formulaire devrait être branchée à une autre Api ou un autre service.

D'une manière générale du coup, en matère de naming, je supprimerais du `TeeForm` tout ce qui est "opportunity" pour conserver que le "form" (ex: `saveOpportunityForm` devient `saveForm`).
On peut se caler une visio pour en discuter

2024-09-10 17:43 UTC, dolemoine commented on apps/web/src/translations/fr/project.ts
> +      hint: '👋 Expliquez nous votre projet, nous vous mettrons en relation avec un conseiller compétent pour votre demande sur votre territoire.',
praise: bien pensé le rebase du hint pour gérer ça de façon générique dans le form

2024-09-10 17:43 UTC, dolemoine commented on apps/web/src/components/element/form/TeeFormElement.vue
> +<template>
praise: c'est bien pensé d'isolé l'input dans un composant et d'y gérer les priopriétés de façon générique

2024-09-23 13:30 UTC, dolemoine reviewed
praise: super taff de refacto je trouve ! 
quelques commentaires, qui sont plutôt de l'ordre de l'ouverture de discussion que de demande de correction.

2024-09-23 13:30 UTC, dolemoine commented on apps/web/src/components/element/form/TeeForm.vue
> +          :checkbox-value="getCheckboxValue(localForm[fieldKey])"
question/suggestion: est-ce que cette notion de text-value / checkbox-value ne peut pas être gérée directement du côté du `TeeFormElement` ?

On pourrait simplifier en ne passant que le field au `TeeFormElement`, et c'est lui qui serait en charge de gérer si c'est un checkbox ou un text

2024-09-23 13:30 UTC, dolemoine commented on apps/web/src/components/element/form/TeeForm.vue
> +          @update-field="(field) => (localForm[fieldKey] = field)"
question: sur mon IDE, j'ai un warning sur le fait que field n'est pas typé. tu n'as pas ça de ton côté?

2024-09-23 13:30 UTC, dolemoine commented on apps/web/src/components/element/form/TeeForm.vue
> +}
suggestion: gérer cette spécificité de champ de formulaire dans le `TeeFormElement`

2024-09-23 13:30 UTC, dolemoine commented on apps/web/src/components/element/form/TeeFormElement.vue
> +      v-model="localCheckboxValue"
sugggestion: en lien avec mon commentaire sur le `TeeForm` on pourrait donc ici bind le `localField.value`

2024-09-23 13:30 UTC, dolemoine commented on apps/web/src/components/element/form/TeeFormElement.vue
> +        v-model="localTextValue"
idem ici

2024-09-23 13:30 UTC, dolemoine commented on apps/web/src/components/element/form/TeeFormElement.vue
> +  textValue?: string
suggestion: ces props deviendraient obsolètes

2024-09-23 13:30 UTC, dolemoine commented on apps/web/src/components/element/form/TeeFormElement.vue
> +const localTextValue = ref<string | undefined>(props.textValue)
idem

2024-09-23 13:30 UTC, dolemoine commented on apps/web/src/components/element/form/TeeForm.vue
> +  dataSlug: string
suggestion/question: dans le cas du `ProgramDetail`, le `dataId` et le `dataSlug` sont tous les deux le `program.id`. Est-ce qu'on pourrait rendre optionnel le `dataSlug` et prendre utiliser par défaut le `dataId` si `dataSlug` est `undefined` ?

2024-09-23 13:30 UTC, dolemoine commented on apps/web/src/components/element/form/TeeForm.vue
> +  formType: FormType
question: je me demande si on ne pourrait pas inclure le formType dans FormDataType ? est-ce que d'avoir les 2 bien distinct facilite la lecture ou apporte une plus-value dans l'utilisation des composants ?

2024-09-23 13:30 UTC, dolemoine commented on apps/web/src/components/program/detail/ProgramDetail.vue
> +        :form-type="FormType.Program"
note: oublie ce que j'ai dit sur le regroupement du FormType dans le FormDataType, en voyant la logique de récupération des data je me dis que ce n'est pas une bonne idée.

2024-09-23 13:30 UTC, dolemoine commented on apps/web/src/types/genericTypes.ts
> +export enum FieldType {
praise: beau travail sur la refacto des types!

2024-09-23 13:30 UTC, dolemoine commented on apps/web/src/types/opportunityFormType.ts
> +  colSize?: number
note/reflexion: en voyant ça comme ça, je ne sais pas si c'est le mieux de gérer les questions de rendu graphique comme ça... mais je n'ai pas d'autre idée. Sauf peut-être à sortir ces élements pour les mettres dans un type spécifique genre 

```typescript


type FieldRenderingType = {
  wrapperClass?: string
  rows?: number
  colSize?: number
}

type DefaultFieldFormType = {
  required: true
  type: FieldType
  isValid: boolean | undefined
  hidden?: boolean
  label?: string
  hint?: string
  hintLink?: {
    route: RouteName
    text: string
  }
  fieldRendering?: FieldRenderingType
  callOut?: InputCalloutType
}
```

mais en l'écrivant je me dis que ça complexifie pour rien

2024-09-23 13:30 UTC, dolemoine commented on apps/web/src/utils/opportunity.ts
> +import { PhoneValidator, EmailValidator, SiretValidator } from '@tee/common'
praise: nice la classe de définition des champs de formulaire ! j'aime bien la logique.

note pour plus tard: on pourrait imaginer un système avec de l'héritage avec une classe `AbstractOpportunity` par exemple, qui définierait les champs de bases, puis une `ProgramOpportunity` et un `ProjectOpportunity` qui viendraient étendre la classe abstraite en y ajoutant les champs spécifiques.
je me dis que ça pourrait être intéressant si à l'avenir on doit rajouter un autre formulaire.

2024-09-24 08:18 UTC, oumeimaelisbihani commented on apps/web/src/components/element/form/TeeForm.vue
> +          @update-field="(field) => (localForm[fieldKey] = field)"
non j'ai rien !

2024-09-24 08:38 UTC, oumeimaelisbihani commented on apps/web/src/types/opportunityFormType.ts
> +  colSize?: number
Ca me choque pas d'avoir tout dans un même type ! Ca reste assez lisible

2024-09-24 08:42 UTC, oumeimaelisbihani commented on apps/web/src/components/element/form/TeeForm.vue
> +}
c'était parce que ça posait des soucis au niveau du v-model dans le TeeFormElement avec le type boolean incompatible avec le champ v-model du DsfrSelect mais du coup j'ai pu le régler autrement

2024-09-24 09:27 UTC, dolemoine requested changes

2024-09-24 09:27 UTC, dolemoine commented on apps/web/src/components/element/TeeError.vue
> +    <p class="fr-text--red fr-text--md fr-m-0">
praise: nice le remplacement pas des classes css génériques!

2024-09-24 09:27 UTC, dolemoine commented on apps/web/src/components/program/detail/ProgramDetail.vue
> +  console.log(program.value ? Opportunity.getProgramFormFields(program.value) : '')
todo: à supprimer

2024-09-24 09:27 UTC, dolemoine commented on apps/web/src/components/element/form/TeeFormElement.vue
> +  <div
suggestion: je me demande si on gagnerait pas en lisibilité si tu définissais 3 composants enfants : `TeeFormCheckbox`, `TeeFormSelect` et `TeeFormInput` pour séparer les logiques inhérentes à chaque type d'input du formulaire, et de les inclure dans le `TeeFormElement`.
t'en penses quoi ?

2024-09-24 09:27 UTC, dolemoine commented on apps/web/src/components/element/form/TeeForm.vue
> +  dataSlug: string
que penses-tu de cette proposition ?

2024-09-24 09:28 UTC, dolemoine commented
Le changement demandé est simplement pour le console log dans le `ProgramDetail.vue`

2024-09-30 13:51 UTC, oumeimaelisbihani commented on apps/web/src/components/element/form/TeeFormElement.vue
> +  <div
yes c'est plus propre, c'est intégré

2024-09-30 13:54 UTC, oumeimaelisbihani commented on apps/web/src/components/element/form/TeeForm.vue
> +  dataSlug: string
woups je l'avais oublié ! c'est ajouté!

2024-10-02 07:51 UTC, dolemoine commented on apps/web/src/components/element/form/TeeFormElement.vue
> +  <div
praise: chouette la logique pour sélectionner le bon component, j'ai jamais utilisé cette approche

2024-10-02 07:58 UTC, dolemoine approved these changes
praise: beau boulot :clap:

2024-10-03 13:34 UTC, yvalentin requested changes
Vu à l'oral ! Je save les pending pour rappel ;-)

2024-10-09 15:29 UTC, merged