refactor: Refactor to remove DsfrAccordion component (WIP)
betagouv/mission-transition-ecologique pull request #1089
Opened 2024-09-12 14:00 UTC by dolemoine

### Changements
- supprime l'usage du `DsfrAccordion` dans le `ProjectDetail.vue`

### Test

### Issue cloturé
close #948

2024-09-16 18:01 UTC, ttdm approved these changes
Super clean, RAS. 

J'ai juste mis une remarque parce qu'on en discute ailleurs mais c'est vraiment mineur et plus pou ralimenter nos discussions du moment ;)

2024-09-18 08:23 UTC, yvalentin requested changes
todo: Dans le but, d'harmonizer les block de type titre/contenu (voir avec our sans accordéon), un composant Tee(Dsfr) pourrait être mis en place.

Avec par exemple (??):
- le titre en props
- le contenu en slot

2024-09-18 08:48 UTC, dolemoine commented on apps/web/src/components/project/details/ProjectDescription.vue
> +    id="project-more-details-title"
ce sera en partie réglé avec la création d'un composant TeeContent (ou qq chose du genre) comme proposé par Yohann.

Gardons en mémoire ce sujet de spacing styling pour cette fin de journée

2024-09-23 13:46 UTC, yvalentin requested changes
Pas besoin de me remettre en approuve après ;-)

2024-09-23 13:46 UTC, yvalentin commented on apps/web/src/components/element/TeeContentBlock.vue
> +})
todo: la valeur par défaut devrait déjà être à `undefined`, il semblerais alors que le `withDefault` soit inutile

2024-09-23 13:46 UTC, yvalentin commented on apps/web/src/types/border.ts
> +}
praise: pour la définition d'un enum

2024-09-23 13:46 UTC, yvalentin commented on apps/web/src/components/project/details/ProjectDescription.vue
> +    :key="getRandomId(index)"
suggestion: la key pourrait être la même que l'id ?

2024-09-23 13:49 UTC, yvalentin commented on apps/web/src/components/element/TeeContentBlock.vue
> +.tee-border {
suggestion: possiblilité de faire une classe `fr-border` à la place...

2024-09-24 09:30 UTC, merged