Refactor/program type
betagouv/mission-transition-ecologique pull request #1093
Opened 2024-09-17 14:31 UTC by dolemoine

2024-09-29 22:42 UTC, ttdm requested changes
Suggestion : dans le front, changer, lorsque c'est possible les 'value as string' par value || ''    

Request : 
Pourquoi 'ProgramTypeWithPublicodes' dans le back ? C'est assez logique que le ProgramType par défaut du back ai du publicodes !  
Dans le back programTypeWithPublicodes devrait être rennomé programType. 
(Dans le back, Le ProgramType du front par exemple s'appelle bien 'frontProgram'. (voir le fichier converter)).

 ça me semble sain que le même nom, qui est le meilleur nom parce que le plus simple, puisse désigner deux type différent dans chaque package.

2024-09-29 22:42 UTC, ttdm commented on apps/web/src/types/genericTypes.ts
> +export type Override<T, NewType> = Omit<T, keyof NewType> & NewType
praise,

2024-09-29 22:42 UTC, ttdm commented on apps/web/src/components/program/list/ProgramCard.vue
> +      text = program["montant de l'avantage fiscal"] as string
Tu peux supprimer les as string et ajouter if (!text) text = ''

2024-09-29 22:42 UTC, ttdm commented on apps/web/src/components/program/detail/ProgramLongDescription.vue
>    const textRaw = props.program['description longue']
const textRaw = props.program['description longue'] || '' ?

2024-09-29 22:42 UTC, ttdm commented on apps/web/src/components/program/detail/ProgramHeader.vue
> +  return [...links, { text: (props.program?.titre as string) || '' }]
inutile ?

2024-10-02 14:34 UTC, dolemoine commented on apps/web/src/components/program/list/ProgramCard.vue
> +      text = program["montant de l'avantage fiscal"] as string
j'ai une erreur de typage si je ne précise pas que les valeurs sont du string: 
```shell
src/components/program/list/ProgramCard.vue(62,9): error TS2322: Type '{}' is not assignable to type 'string'.
src/components/program/list/ProgramCard.vue(66,9): error TS2322: Type 'unknown' is not assignable to type 'string | undefined'.
src/components/program/list/ProgramCard.vue(71,7): error TS2322: Type 'unknown' is not assignable to type 'string | undefined'.
src/components/program/list/ProgramCard.vue(75,7): error TS2322: Type 'unknown' is not assignable to type 'string | undefined'.
src/components/program/list/ProgramCard.vue(79,7): error TS2322: Type 'unknown' is not assignable to type 'string | undefined'.
src/components/program/list/ProgramCard.vue(83,7): error TS2322: Type 'unknown' is not assignable to type 'string | undefined'.

```

2024-10-02 14:42 UTC, dolemoine commented on apps/web/src/components/program/detail/ProgramHeader.vue
> +  return [...links, { text: (props.program?.titre as string) || '' }]
idem j'ai une erreur sur le type:check si je précise pas que props.program?.titre est de type string

2024-10-02 16:09 UTC, ttdm commented on apps/web/src/components/program/list/ProgramCard.vue
> +      text = program["montant de l'avantage fiscal"] as string
t'as build ton projet ?

2024-10-03 07:30 UTC, dolemoine commented on apps/web/src/components/program/list/ProgramCard.vue
> +      text = program["montant de l'avantage fiscal"] as string
ok je teste ça !

2024-10-03 07:47 UTC, dolemoine commented
J'ai apporté les modifs dont tu parlais notamment sur les typing dans les templates. ça passe ici mais ça passe pas mes type:check:vue en local.
ça m'embête un peu de push du code qui passe pas tous les checks, surtout que j'ai pas l'impression que le type check soit encore fait sur la CI.
T'en penses quoi?

2025-01-20 08:40 UTC, dolemoine commented
une nouvelle PR sera ouverte avec la reprise du ticket sur nuxt

2025-01-20 08:40 UTC, closed without merging