Feat: programs conditionnels
betagouv/mission-transition-ecologique pull request #1122
Opened 2024-09-20 14:38 UTC by ttdm

Main feature: 
- ajout de la prise en compte de programmes conditionnels

Détail des features : 
- lecture de la nouvelle table baserow programme conditionnels et conversion vers le format du domain de data.
- ajout d'une section champs conditionnels dans le yaml et ajout d'un generateur pour créer cette section.
- ajout d'une fonction getAllPersonalizedPrograms dans le backend qui évalue les conditions et réalise une modification du contenu programme si les conditions le demandent. (Note : réalisé via du traitement sur les strings, ce serait réalisable en publicodes mais horrible au niveau perf et long et complexe à mettre en place)

- Mineur : suppression d'une entrée taux de prêt historique et non utilisée à présent. 

Point à noter : 
- le package data pourrait bénéficier d'améliorations / diverses refacto mais j'ai une autre grosse PR dans laquelle j'en fais donc j'ai plutôt choisi de limiter les refacto içi pour limiter les conflits. Sentez vous libre de commenter sur ces refactos, je les mettrai pour la plupart en place sur l'autre ticket. 

close #390

2024-09-23 15:16 UTC, oumeimaelisbihani commented on libs/backend-ddd/src/program/infrastructure/programsJson.ts
> +    if (conditionalChange['opérateur de contact']) {
est ce que pour opérateur de contact, autres opérateurs et url on pourrait pas faire une boucle avec les clefs puis boucler dessus ? 
```
keys.forEach((key) => {
    if (conditionalChange[key]) {
      program[key] = conditionalChange[key]
    }
  }) 
```

2024-09-23 15:16 UTC, oumeimaelisbihani commented on libs/backend-ddd/src/program/infrastructure/programsJson.ts
> +    Monitor.error('Unknown condition type in conditional programs', { condition })
est ce que pour la gestion d'erreur on pourrait pas plutot faire une fonction: 

```
private _isValidConditionFormat(condition: string): boolean {
  // Vérifie que la condition contient un format valide
  return condition.startsWith('région = ') || condition.startsWith('effectif');
}
```

2024-09-23 15:16 UTC, oumeimaelisbihani commented on libs/backend-ddd/src/program/infrastructure/programsJson.ts
> +      const comparisonValue = parseInt(condition.split('=')[1].trim())
Est ce que la comparaison de valeur pourrait se faire dans une fonction à part pour plus de lisibilité un truc dans le style
`private _getComparisonValue(condition: string): number | null {
  const comparisonPart = condition.split('=')[1]?.trim();
  const comparisonValue = parseInt(comparisonPart, 10);
  return isNaN(comparisonValue) ? null : comparisonValue;
}`

2024-09-23 15:16 UTC, oumeimaelisbihani commented on libs/backend-ddd/src/program/infrastructure/programsJson.ts
> +        Monitor.error('Formatting error in a conditional Program condition', { condition })
peut etre mettre la gestion d'erreur dans une fonction à part pour facilement le réutiliser ?

2024-09-27 12:38 UTC, ttdm commented on libs/backend-ddd/src/program/infrastructure/programsJson.ts
> +    if (conditionalChange['opérateur de contact']) {
J'ai galéré avec le typage x) 
La solution proposée est la seule solution qui fonctionne par rapport à tous les casts possibles !

2024-09-27 12:46 UTC, ttdm commented on libs/backend-ddd/src/program/infrastructure/programsJson.ts
> +    Monitor.error('Unknown condition type in conditional programs', { condition })
Je l'ai pris, écrit puis supprimé. 
Le problème de cette structure c'est que les conditions sont écrites à 2 endroits différents dans le code ce qui pourrait créer des erreurs lors de l'évolution du code. 
Une manière propre de faire serait de créer une structure qui contient, la type de la condition, sont format pour validation et la function à appliquer pour checker la condition mais c'est un peu complexe pour 2 types de condition. 

Je garde la structure en tête s'il y a plus de conditions dans le futur.

2024-09-27 13:02 UTC, ttdm commented on libs/backend-ddd/src/program/infrastructure/programsJson.ts
> +      const comparisonValue = parseInt(condition.split('=')[1].trim())
C'est fait.

2024-09-27 13:04 UTC, ttdm commented on libs/backend-ddd/src/program/infrastructure/programsJson.ts
> +        Monitor.error('Formatting error in a conditional Program condition', { condition })
La condition est simplifiée avec le reste des modifs et Monitor est déjà une classe spécifique donc ça devait être bon maintenant :)

2024-09-30 09:04 UTC, oumeimaelisbihani approved these changes

2024-10-07 08:42 UTC, yvalentin requested changes

2024-10-07 08:42 UTC, yvalentin commented on libs/common/src/questionnaire/types/types.ts
> +export const StructureSizeMap: { [key in StructureSize]: number } = {
question: Est-ce que c'est possible de mutualiser ?

```ts
// libs/backend-ddd/src/program/infrastructure/preprocessProgramsPublicodes.ts:15
const SizeToWorkforce: { [key in StructureSize]: number } = {
  [StructureSize.EI]: 1,
  [StructureSize.TPE]: 19,
  [StructureSize.PE]: 49,
  [StructureSize.ME]: 249,
  [StructureSize.ETI_GE]: 251
}
```

2024-10-07 08:42 UTC, yvalentin commented on libs/data/src/program/conditionalDataGenerator.ts
> +    const conditionGeographique = oneConditional['valeur de la condition géographique']
typo: conditionGeographic ?

2024-10-07 08:42 UTC, yvalentin commented on libs/data/src/program/types/domain.ts
> +export interface ConditionalValues {
question: Tous les champs ne semble pas obligatoire. Du coup, certains champs devraient être à `undefined` ?

2024-10-07 08:42 UTC, yvalentin commented on libs/data/src/program/types/domain.ts
> +  'Dispositif concerné': string
question: De plus, je vois que dans baserow en fonction du "Type de condition" les champs remplie ne sont pas les mêmes. Est-ce qu'il serait intéressant d'avoir des type TS par type de condition ?

2024-10-07 08:42 UTC, yvalentin commented on libs/data/src/program/conditionalDataGenerator.ts
> +  private _generateGeographicCondition(oneConditional: ConditionalValues): any {
question: Ces retours pourraient être typé ?

2024-10-07 14:17 UTC, ttdm commented on libs/backend-ddd/src/program/infrastructure/programsJson.ts
> +    allPrograms.forEach((program) => {
J'ai une erreur TypeAnnotation canno't appear in a constructor sur l'argument programs. 
Du coup, j'ai laissé une méthode getAllPersonalizedPrograms et le call est : 
`new ProgramCustomizer().getAllPersonalizedPrograms(editablePrograms, questionnaireData)`

2024-10-07 14:28 UTC, ttdm commented on libs/backend-ddd/src/program/infrastructure/programsJson.ts
> +    if (!structure_size) {
Je suis d'avis de le laisser pour justement avoir des erreurs si jamais on se trompe en modifiant la méthode de vérification "shouldRewritePrograms".

2024-10-07 14:32 UTC, ttdm commented on libs/data/src/program/types/domain.ts
> +export interface ConditionalValues {
Répondu en visio, baserow retourne une valeur nulle pour des champs vides (donc '' pour une string)

2024-10-07 17:10 UTC, ttdm commented
2 problèmes détectés lors d'une étape de vérification manuelle : 
- Pas de prise en compte des programmes conditionnels sur les getOne ! En particulier quand on revient sur une fiche via une url. 
- problème de modifs qui deviennent semi permanentes au lieu de s'appliquer à une seul requête. Relire le fichier json n'a pas l'air de fonctionner comme prévu. 

Liens intéressants pour faciliter les tests : 
Tests sur l'effectif : 
(la valeur qui change étant le cout, il est visible sur la page générale du questionnaire résultat ce qui permet de tester sa présence aussi )
[Pour une petite entreprise](https://tee-preprod-pr1122.osc-fr1.scalingo.io/questionnaire/resultat?choix-du-parcours=je-ne-sais-pas-par-ou-commencer&siret=77561483700133&effectif=PE&locaux=locataire&mobilite=oui&matieres-premieres=oui&tri-dechets=non&dechets=oui&gestion-eau=oui&energie=oui&audit=non#questionnaire-resultat), présence de eco-flux, texte 2000€ ...
[Pour une entreprise de taille moyenne](https://tee-preprod-pr1122.osc-fr1.scalingo.io/questionnaire/resultat?choix-du-parcours=je-ne-sais-pas-par-ou-commencer&siret=77561483700133&effectif=ME&locaux=locataire&mobilite=oui&matieres-premieres=oui&tri-dechets=non&dechets=oui&gestion-eau=oui&energie=oui&audit=non#questionnaire-resultat) présence de eco-flux, texte 3000€ ...
[pour une eti](https://tee-preprod-pr1122.osc-fr1.scalingo.io/questionnaire/resultat?choix-du-parcours=je-ne-sais-pas-par-ou-commencer&siret=77561483700133&effectif=ETI_GE&locaux=locataire&mobilite=oui&matieres-premieres=oui&tri-dechets=non&dechets=oui&gestion-eau=oui&energie=oui&audit=non#questionnaire-resultat), filtrage valide, pas de présence d'éco flux. 
[pour une ei](https://tee-preprod-pr1122.osc-fr1.scalingo.io/questionnaire/resultat?choix-du-parcours=je-ne-sais-pas-par-ou-commencer&siret=77561483700133&effectif=EI&locaux=locataire&mobilite=oui&matieres-premieres=oui&tri-dechets=non&dechets=oui&gestion-eau=oui&energie=oui&audit=non#questionnaire-resultat), filtrage valide, pas de présence d'éco flux. 
[sur l'annuaire](https://tee-preprod-pr1122.osc-fr1.scalingo.io/aides-entreprise/diag-eco-flux), texte de 2000€ à 3000€

Tests sur la région : 
[en bretagne](https://tee-preprod-pr1122.osc-fr1.scalingo.io/questionnaire/resultat/performa-environnement?choix-du-parcours=j-ai-un-projet&siret=siret-non-renseigne&effectif=TPE&activite=tertiaire&region=Bretagne&objectifs=environmental), texte: 1journée
[en auvergne rhone alpes ](https://tee-preprod-pr1122.osc-fr1.scalingo.io/questionnaire/resultat/performa-environnement?choix-du-parcours=j-ai-un-projet&siret=siret-non-renseigne&effectif=TPE&activite=tertiaire&region=Auvergne-Rh%C3%B4ne-Alpes&objectifs=environmental), texte: 2jorus sur 6mois
[annuaire](https://tee-preprod-pr1122.osc-fr1.scalingo.io/aides-entreprise/performa-environnement) texte, 1 journée

2024-10-28 14:45 UTC, ttdm commented
Dernière request de review, PR complètement fonctionnelle. 
la totalité des remarques faites ont été prises en compte / ont donné lieu à des réponses. 

Et merci pour le coup de main sur la partie front :)

2024-10-30 09:27 UTC, merged

2024-10-30 09:28 UTC, ttdm commented
Note : validation fonctionnelle réalisé avant le merge par coline et PR validée au niveau technique en visio par Yohann.