Feat : Sur un projet, afficher tous les dispositifs liés, si aucune data entreprise
betagouv/mission-transition-ecologique pull request #1125
Opened 2024-09-23 10:22 UTC by oumeimaelisbihani

- Changement de la condition d'affichage du formulaire de contact dans le detail d'un projet 
- Changement de la condition d'affichage de la liste des dispositifs dans le détail d'un projet

2024-09-23 12:15 UTC, dolemoine approved these changes
Nickel pour moi

2024-09-23 14:05 UTC, yvalentin requested changes

2024-09-23 14:05 UTC, yvalentin commented on apps/web/src/components/project/details/ProjectPrograms.vue
> +    <div class="fr-container--fluid">
todo: Il semble le `container--fluid` ne soit pas necessaire. Il doit être possible de supprimer cette div

2024-09-23 14:05 UTC, yvalentin commented on apps/web/src/components/project/details/ProjectPrograms.vue
> +        <div class="fr-container--fluid fr-p-4v">
todo: Il semble le `container--fluid` ne soit pas necessaire. La classe `fr-p-4v` doit pouvoir aller sur la div du dessous et donc possiblité de supprimer cette div

2024-09-23 14:05 UTC, yvalentin commented on apps/web/src/components/project/details/ProjectPrograms.vue
> +      v-if="!isCatalogDetail"
todo: Il semble possible d'utilise de `v-else` ici ?

2024-09-25 14:54 UTC, yvalentin approved these changes

2024-10-02 08:29 UTC, dolemoine reviewed
juste deux questions de mon côté, et une note pour qu'on garde une trace sur un sujet de refacto. 
sinon RAS, c'est ok pour moi

2024-10-02 08:29 UTC, dolemoine commented on apps/web/src/components/project/details/ProjectPrograms.vue
> +          </div>
note: c'est juste pour garder une trace, mais il faudrait probablement qu'on fasse un petit taff de refacto sur cette partie qu'on retrouve à plusieurs endroit pour avoir un composant générique qui nous gère le spinner, l'erreur et le no result

2024-10-02 08:29 UTC, dolemoine commented on apps/web/src/stores/navigation.ts
> +    return isByRouteName([RouteName.ProgramFromProjectDetail, RouteName.CatalogProgramFromCatalogProjectDetail])
question: est-ce que ça ne crée pas de conflit d'avoir un même RouteName dans deux méthodes ? 
`RouteName.CatalogProgramFromCatalogProjectDetail` dans `isCatalogProgramDetail` et dans `isProgramFromProject`

2024-10-02 08:29 UTC, dolemoine commented on apps/web/src/components/program/detail/ProgramHeader.vue
> +const isCatalogDetail = navigationStore.isCatalogProgramDetail()
question: 
si j'ai accédé au détail d'un program depuis une fiche projet, ici `isCatalogDetail` est `true` puisque que `RouteName.CatalogProgramFromCatalogProjectDetail` fait bien partie des routes dans la méthode `isCatalogProgramDetail` du  `navigationStore`.
avec la logique du code qui suit, `routeToResults` me redirigera donc sur la listes des aides et pas la liste des projets, or je viens de la liste des projets.
Est-ce que ce n'est pas problématique ? Je trouve ça un peu étrange d'un point de vue fonctionnel, mais vous avez peut-être validé ça comme ça avec Coline.

2024-10-02 09:20 UTC, oumeimaelisbihani commented on apps/web/src/stores/navigation.ts
> +    return isByRouteName([RouteName.ProgramFromProjectDetail, RouteName.CatalogProgramFromCatalogProjectDetail])
je pense pas non !

2024-10-02 12:47 UTC, oumeimaelisbihani commented on apps/web/src/components/program/detail/ProgramHeader.vue
> +const isCatalogDetail = navigationStore.isCatalogProgramDetail()
en effet c'était pas logique ! c'est modifié!

2024-10-02 13:00 UTC, yvalentin commented on apps/web/src/components/project/details/ProjectPrograms.vue
> +          </div>
Oui, il faudra lui trouver un jolie nom à ce composant ^^

2024-10-02 13:29 UTC, dolemoine approved these changes
Ok pour moi!

2024-10-02 13:35 UTC, yvalentin approved these changes

2024-10-02 14:16 UTC, merged