feat: Add company data persistence using local storage
betagouv/mission-transition-ecologique pull request #1195
Opened 2024-10-04 14:00 UTC by dolemoine

Résumé: 

Cette pull request introduit des changements significatifs pour améliorer la gestion et la persistance des données de l'entreprise au sein de l'application. Les changements les plus importants incluent l'ajout d'un nouveau store pour les données de l'entreprise, l'intégration de la persistance des données de l'entreprise dans divers composants, et la création de classes utilitaires et d'interfaces pour la gestion du stockage.

Améliorations de la gestion des données de l'entreprise :

* [`apps/web/src/stores/companyData.ts`](diffhunk://#diff-7ddf902b278e4f341780751b64c00ea0bae8a4f60b8225b302379325f8aa4b3cR1-R50) : Introduction d'un nouveau store pour gérer les données de l'entreprise, incluant des méthodes pour définir, obtenir et effacer les données.
* [`apps/web/src/types/companyDataType.ts`](diffhunk://#diff-e951ac57b1040766663e716970aacae922d4d063d9e19eb80090deb3e02ea4edR1-R12) : Ajout de nouveaux types et énumérations pour les clés et identifiants des données de l'entreprise.

Intégration de la persistance des données de l'entreprise :

* [`apps/web/src/components/project/details/ProjectPrograms.vue`](diffhunk://#diff-273e7306716f6bd82bb320ed7a6e38357e218aa4acf2f85d34cbce6d169e1639L41-R41) : Mise à jour pour vérifier la présence des données de l'entreprise et importer l'utilitaire `CompanyData`. [[1]](diffhunk://#diff-273e7306716f6bd82bb320ed7a6e38357e218aa4acf2f85d34cbce6d169e1639L41-R41) [[2]](diffhunk://#diff-273e7306716f6bd82bb320ed7a6e38357e218aa4acf2f85d34cbce6d169e1639R90) [[3]](diffhunk://#diff-273e7306716f6bd82bb320ed7a6e38357e218aa4acf2f85d34cbce6d169e1639R100)
* [`apps/web/src/stores/usedTrack.ts`](diffhunk://#diff-5942c8a1e8c6f559986d59fd424cda5d171ec2c6f92340199e7f203c83baf24eR6) : Modification pour persister les données du questionnaire dans le store des données de l'entreprise et vérifier les données existantes de l'entreprise lors de l'initialisation. [[1]](diffhunk://#diff-5942c8a1e8c6f559986d59fd424cda5d171ec2c6f92340199e7f203c83baf24eR6) [[2]](diffhunk://#diff-5942c8a1e8c6f559986d59fd424cda5d171ec2c6f92340199e7f203c83baf24eR21-R23) [[3]](diffhunk://#diff-5942c8a1e8c6f559986d59fd424cda5d171ec2c6f92340199e7f203c83baf24eR113-R121) [[4]](diffhunk://#diff-5942c8a1e8c6f559986d59fd424cda5d171ec2c6f92340199e7f203c83baf24eL207-R221) [[5]](diffhunk://#diff-5942c8a1e8c6f559986d59fd424cda5d171ec2c6f92340199e7f203c83baf24eR267-R275)
* [`apps/web/src/types/track/trackType.ts`](diffhunk://#diff-e7d58ff08c7c6ddab4ffa615f08c67c130305cfb170162a54ac329fcc9333461R203) : Ajout d'un champ optionnel `isPersisted` à l'interface `UsedTrack`.

Création de classes utilitaires et d'interfaces :

* [`apps/web/src/utils/storage/StorageHandlerInterface.ts`](diffhunk://#diff-c68aefd25e578c405c5f14399615a79a8939b1330f3cace934e8bb7d93a0c174R1-R7) : Définition d'une nouvelle interface pour les gestionnaires de stockage afin de standardiser les méthodes de définition, d'obtention et d'effacement des données.
* [`apps/web/src/utils/storage/companyData.ts`](diffhunk://#diff-22c66473b460f2a2ef3958c9ddd8f63f7ad5f59aac814015ff2f822a0150ddfcR1-R14) : Implémentation de la classe `CompanyData` pour fournir des méthodes statiques permettant de vérifier la persistance et la disponibilité des données.
* [`apps/web/src/utils/storage/localStorageHandler.ts`](diffhunk://#diff-56bf1f783c1415275b4c6d848508e77a0cadc5f3ebb974384a9dd18966721f4bR1-R45) : Création de la classe `LocalStorageHandler` pour gérer les opérations de stockage local, en implémentant l'interface `StorageHandlerInterface`.

App test :
[https://tee-preprod-pr1194.osc-fr1.scalingo.io/](https://tee-preprod-pr1194.osc-fr1.scalingo.io/)

Issue liée : 

#1090

2024-10-04 14:36 UTC, dolemoine commented
Note: vous êtes tagg sur la PR en draft pour avis tech sur l'approche (et discussion si nécessaire) avant de la passer en review

2024-10-14 13:46 UTC, yvalentin requested changes
Des petites choses à revoir. On peux en discuter !

Je vois qu'il manque un set de la "company size" quand on est un `EI`. Mais c'est aussi parce qu'il y un pb sur le sujet (Je fais un PR pour ça)

2024-10-14 13:46 UTC, yvalentin commented on apps/web/src/utils/storage/companyDataStorage.ts
> +    this._data.value = this._storageHandler.getAll() || {}
todo: on devrait récupérer uniquement les data en relation avec la companie. Là on récupere tout le local storage...

```ts
const siret = this.getItem(CompanyDataId.Siret) as unknown as EstablishmentFront | null
const size = this.getItem(CompanyDataId.Size) as StructureSize | null
if (siret) {
  this._data.value.siret = siret
}

if (size) {
  this._data.value.structure_size = size
}
```

2024-10-14 13:46 UTC, yvalentin commented on apps/web/src/stores/usedTrack.ts
> +    if (CompanyDataStorage.hasData() && !useNavigationStore().isByRouteName([RouteName.Questionnaire, RouteName.QuestionnaireResult])) {
question: est-ce que cette partie est utile pour la tache/issue en cours ?

2024-10-14 13:46 UTC, yvalentin commented on apps/web/src/utils/storage/localStorageHandler.ts
> +      console.log('Error while retrieving localStorage item', e)
question: est-ce que c'est normal d'avoir laisser les console.log ?

2024-10-14 19:02 UTC, dolemoine commented on apps/web/src/utils/storage/companyDataStorage.ts
> +    this._data.value = this._storageHandler.getAll() || {}
j'ai pris en compte ta proposition mais en utilisant une const data dans la fonction pour pouvoir return un `Ref` (cf remarque au début de cette classe sur le `private static readonly _data`)

2024-10-14 19:05 UTC, dolemoine commented on apps/web/src/stores/usedTrack.ts
> +    if (CompanyDataStorage.hasData() && !useNavigationStore().isByRouteName([RouteName.Questionnaire, RouteName.QuestionnaireResult])) {
ici on récupère les données stockées pour les réinjecter dans le questionnaire data pour qu'elles soit prises en compte dans les appels API.
je dirais que ça va bien dans cette PR comme un des criètes d'acceptabilité est d'avoir l'info d'éligibilité sur le catalogue des aides. t'en penses quoi ?

2024-10-14 19:06 UTC, dolemoine commented on apps/web/src/utils/storage/localStorageHandler.ts
> +      console.log('Error while retrieving localStorage item', e)
à la base oui, pour avoir l'info dans la console s'il y a une erreur. je peux le virer si tu préfères, idem sur le `getAll()`

2024-10-14 19:07 UTC, dolemoine commented
> Je vois qu'il manque un set de la "company size" quand on est un EI. Mais c'est aussi parce qu'il y un pb sur le sujet (Je fais un PR pour ça)

pour ce point-là est-ce qu'on peut en discuter pour voir quelle approche avoir ?

2024-10-15 18:37 UTC, yvalentin approved these changes

2024-10-16 07:37 UTC, dolemoine commented
@yvalentin au final je ne vais pas merge dans main, mais j'ai push dans feat/user-data-demo qui sera la branche de demo

2024-10-16 08:25 UTC, merged