Feat: filter projects by establishement sector
betagouv/mission-transition-ecologique pull request #1213
Opened 2024-10-12 12:08 UTC by ttdm

Features principales : 
- ajout de données sur l'égibilité sectorielle dans baserow dans la table projets
- création d'une entrée "sectors" dans les données projets
- création d'un point API qui filtre les secteurs en fonction du codeNaf1 ou du secteur choisit manuellement
- évolution des filtrages des projets dans le front : 
  1. supression du filtre qui cache le projet si aucun dispositif n'est éligible lorsqu'il était utilisé
  2. Ajout d'un filtre qui cache le projet si son secteur ne correspond pas au secteur de l'entreprise.

Vérification effectuées : 
Web E2E :
- Sachant que tous les projets sont bien éligibles pour tous les secteurs pour l'instant dans baserow, j'ai vérifié que tous les projets sont bien visibles dans les onglets résultat, même quand il n'y a pas de programmes éligibles. par exemple ici : http://localhost:4242/questionnaire/resultat/projet/vegetalisation?choix-du-parcours=j-ai-un-projet&siret=83014132100034&effectif=TPE&objectifs=biodiversite
- J'ai manuellement supprimé l'entrée "sectors" de 'diag-360' et je constate bien que le projet est dispo dans le catalogue mais pas dans les résultats des deux questionnaires.

Vérif data: 
- Suppression d'un secteur dans baserow supprime bien la lettre associé dans l'entrée secteur du json project créé. 

Vérif backend: 
- En supprimant manuellement des secteurs, certains projets ne sont pas retournés par le point d'API.
- Tests de l'API effectués avec l'entrée `Codenaf` et avec `Sectors`

Features secondaires : 
- ajouts de tags swagger pour avoir un swagger qui sépare les points d'api dans des catégories différentes et la possibilité de voir les détails d'un seul point d'api. 

Points qui questionnent : 
- dans le front, j'ai vraiment du mal avec l'archi API/stores/utilisation des store dans les composants. Je pense qu eje me suis conformé à l'archi mais n'éhsitez pas à réagir. 
- dans le front dans `ProgramDetails.vue`, l'appel au store, entre `projects` et `eligibileProjects` devrait surement dépendre de l'URL. Par défaut si questionnaireData est vide, `eligibileProjects == projects` donc la PR semble fonctionnelle. Mais 1/ je ne suis pas sur que questionnaireData soit toujours clear quand on est sur le catable et 2/ de toute manière, ça ne me semble pas terrible de se reposer sur cela au niveau archi. Si a vous semble une bonne idée, Je veux bien que quelqu'un m'aide sur les 2 lignes nécessaire pour checker l'url et alterner entre `projectStore.projects` et `projectStore.eligibileProjects`

2024-10-15 15:32 UTC, oumeimaelisbihani commented on apps/web/src/components/program/detail/ProgramDetail.vue
> +  const projectResult = await projectStore.eligibleProjects
[suggestion] : le check pourrait se faire avec la RouteName ?  RouteName.CatalogProgramDetail si on est dans le catalog et RouteName.QuestionnaireResult sinon ?

2024-10-15 15:37 UTC, oumeimaelisbihani commented
@ttdm ça m'a l'air ok pour moi pour l'articulation api/store/component ! j'ai juste mis une question mais sinon c'est ok !

2024-10-16 19:53 UTC, ttdm commented on apps/web/src/components/program/detail/ProgramDetail.vue
> +  const projectResult = await projectStore.eligibleProjects
Probablement, vous savez mieux que moi comment fonctionne le front. Vous savez aussi mieux que moi quel component est affiché sur quelle page :)  
Si tu me dis que ça a plus de sens de  faire ce filtrage, très bien je le fais ! :)
Je passe yohann en review.

2024-10-17 15:14 UTC, yvalentin requested changes

2024-10-18 13:58 UTC, ttdm commented
Du coup la PR est prête, validé à l'oral par Yohann. Comme on a le temps, j'ai refait une review request pour une validation directe.

J'ai laissé une note à JB et à manon. S'ils ont modifié la donnée et souhaitent avoir une démo pendant ma semaine de vacances, il suffit de lancer la commande `run npm generate:projects` puis de commit le fichier mis à jour. 
Une fois validé de leur coté et s'ils n'ont pas de remarques, ça peut être merge en prod.

2024-10-21 20:13 UTC, yvalentin approved these changes

2024-10-21 20:13 UTC, yvalentin commented on apps/backend/src/controller/project/projectsController.ts
> +  private _validateData(filterData: ProjectFilterQuery): boolean {
praise: super pour la validation ! Merci

2024-10-21 20:13 UTC, yvalentin commented on libs/data/src/program/types/domain.ts
> +export interface DataProgram extends BaserowSectors {
praise: nice !

2024-11-21 16:19 UTC, merged