Feat: CTA other projects backend (with frontend merged)
betagouv/mission-transition-ecologique pull request #1214
Opened 2024-10-13 22:28 UTC by ttdm

Feature principale : 
- Ajout d'un 3ème type d'opportunité possible 

Feature technique majeure : 
- Refacto de nombreux éléments de la gestion d'opportunité dans le backend avec notamment l'ajout d'une classe OpportunityAssociatedObject qui permet une meilleure gestion des différetns payloads associés aux opportunité

Petit bonus sympa : 
- maj de la valeu rpar défaut du point d'api opporutnité de swagger qui est de nouveau utilisable

Test effectués : 
- A partir de swagger : créations d'opportunité des 3 types, vérification de la prise en compte de chaque type d'opportunité dans le compte des opportunités transmises et donc vérification de la limite de transmission à 1 opportunité/joru et par contact à PDE. 
- Tests depuis le front INCORRECTS

ATTENTION : La PR n'est pas fonctionnelle, 

Remarque : le Theme n'est pas utilisé dans le backend. Clarifier les souhaits de l'équipe par rapport à ce champ !

2024-10-16 21:58 UTC, ttdm commented
@oumeimaelisbihani  Je propose qu'on fasse une review croisée ? 
Tu fais la review du back et je fais le front ? 

Puis on tag yohann ensuite ?

2024-10-17 12:39 UTC, oumeimaelisbihani approved these changes

2024-10-17 12:40 UTC, oumeimaelisbihani commented
@ttdm revue faite de mon côté ! j'arrive toujours pas à voir pourquoi playwright ça marche pas!

2024-10-18 21:05 UTC, ttdm commented on libs/backend-ddd/src/opportunityHub/infrastructure/api/placedesentreprises/placeDesEntreprises.ts
> +      opportunity.linkToCatalog = 'https://mission-transition-ecologique.beta.gouv.fr/custom'
ça pourrait être défini dans le front pour que 'https://mission-transition-ecologique.beta.gouv.fr/' soit dynamique. Je suis d'accord !

2024-10-18 21:06 UTC, ttdm commented on libs/backend-ddd/src/opportunityHub/infrastructure/api/placedesentreprises/placeDesEntreprises.ts
> +      maybePayload = this._createProjectRequestBody(opportunity, opportunityData.data.title, opportunityData.data.mainTheme)
On a besoin de celui de base pour pouvoir ensuite retrouver le projet depuis brevo. 
Le titre utilisateur devrait être stocké dans brevo et permettra de faire des stats.

2024-10-18 21:16 UTC, ttdm commented on apps/web/src/components/project/list/ProjectList.vue
> -
Probablement à revert.

2024-10-18 21:20 UTC, ttdm commented on apps/web/src/components/questionnaire/result/list/ResultProjectList.vue
> +            name="fade"
l'arguement fade n'as pas l'air de faire quelque chose chez moi.

2024-10-18 21:22 UTC, ttdm commented on apps/web/src/translations/fr.ts
> -    }
:+1:

2024-10-18 21:26 UTC, ttdm commented on apps/web/src/components/project/list/OtherProjectForm.vue
> +      :error-email-subject="Translation.t('form.errorEmail.subject', { titre: '' })"
Question : les traductions vont bien chercher dans project ?

2024-10-18 21:29 UTC, ttdm commented
Je n'ai pas grand chose à dire non plus dans ma review :) 
J'ai fais des tests fonctionnel end to end qui sont OK. 
ça me semble être OK pour passer à Yohann en début de semaine prochaine :)

2024-10-21 08:32 UTC, oumeimaelisbihani commented on apps/web/src/components/project/list/OtherProjectForm.vue
> +      :error-email-subject="Translation.t('form.errorEmail.subject', { titre: '' })"
les traductions sont dans otherProject ! et pour les phrases génériques dans form.

2024-10-21 14:39 UTC, oumeimaelisbihani commented
@yvalentin je te mets en review malgré que les tests playwright ne marchent pas parce que j'arrive pas à comprendre pourquoi ils marchent pas, les tests fonctionnels passent bien, si je teste les requetes playwright ratées ça marche et @ttdm a aussi fait des tests fonctionnels et ça marche !

2024-10-28 11:21 UTC, yvalentin requested changes
Praise: Gros boulot !! Bravo !!

2024-10-28 11:21 UTC, yvalentin commented on libs/backend-ddd/src/opportunity/domain/opportunityFeatures.ts
> +            title: opportunity.titleMessage || 'No title',
question: d'un côté, on l'a en `fr` ('Projet sans Titre') et ici c'est `No title` (c'est normal)

2024-10-28 11:21 UTC, yvalentin commented on libs/backend-ddd/src/opportunity/infrastructure/api/brevo/brevoMail.ts
> +      email.params = this._paramsProject(opportunity, associatedData.data as CustomProject)
suggestion: `as (Project | CustomProject)`

2024-10-28 11:21 UTC, yvalentin commented on libs/backend-ddd/src/opportunity/infrastructure/api/brevo/brevoMail.ts
> +  private _paramsProject(opportunity: Opportunity, data: CustomProject) {
suggestion: `(..., data: Project | CustomProject)`

2024-10-28 11:34 UTC, ttdm commented on libs/backend-ddd/src/opportunity/domain/opportunityFeatures.ts
> +            title: opportunity.titleMessage || 'No title',
Je dirais que c'est deux chose distinctes. 
Dans le front, ça répond à comment on gère le cas dans le front. 
Dans le back c'est comment on gère n'importe quel call, du front ou d'API partenaires / de tests swagger... 
Par contre, Je vais corriger ça en `untitled`  plutôt que `No title` !

2024-10-28 11:38 UTC, ttdm commented on libs/backend-ddd/src/opportunity/infrastructure/api/brevo/brevoMail.ts
> +      email.params = this._paramsProject(opportunity, associatedData.data as CustomProject)
J'ai pris en supprimant le cas et en transformant le type de l'arguement `data` de `_paramsProject` en `data: Project | CustomProject`

2024-10-28 16:09 UTC, oumeimaelisbihani commented on apps/web/src/components/project/list/OtherProjectCta.vue
> +  <TeeDsfrButton
je trouvais ça plus logique d'utiliser partout TeeDsfrButton histoire d'unifier les composants button mais j'ai modifié!

2024-10-30 09:15 UTC, oumeimaelisbihani commented on apps/web/src/translations/fr/project.ts
> +      errorEmail: {
c'est utilisé dans TeeFormCallback

2024-10-30 09:43 UTC, oumeimaelisbihani commented on apps/web/src/components/project/list/OtherProjectCta.vue
> +  <TeeDsfrButton
du coup le composant c'est OtherProjectCta, je pense pas qu'il soit nécessaire d'en faire un supplémentaire

2024-10-30 14:42 UTC, yvalentin approved these changes

2024-10-30 14:42 UTC, yvalentin commented on apps/web/src/components/questionnaire/result/list/ResultProjectList.vue
> +          <Transition
praise: transition ok ;-) !

2024-11-04 15:03 UTC, merged