Feat: refacto program api
betagouv/mission-transition-ecologique pull request #1217
Opened 2024-10-14 11:11 UTC by ttdm

Features : 
- ajoute la possibilité de retourner l'ensemble des programmes, même s'il ne sont pas éligibles (ajout d'un champ `onlyEligible` dans questionnaireData)
- ajoute l'information d'éligibilité dans le retour d'API pour chaque programme, à la fois dans get et dans getOne

Remarques : 
Une fois la modale SIRET mise en place et l'uniformisation des données d'entrée (secteur = naf1, adresse = ville), ça vaudra le coup de se replonger sur les résultat publicodes pour séparer les "unknowns" des "éligibles". ça ne parait pas terrible d'avoir une dizaine de retour publicode = unknown. AU minimum il faudrait juste savoir pourquoi on les a

2024-10-14 11:28 UTC, ttdm commented
Note: sur playwright, l'erreur est lié au catalogue qui aujourd'hui ne retourne pas les programmes dont la date d'éligiblité est dépassé qui ne sont pas retournés ajourd'hui. 

En gros, l'approche proposée est fonctionnelle pour ma PR et le getOneProgram. On retourne toujours le dispositif et on y associe son éligibilité. 
Par contre, pour le getPrograms et pour la partie catalogue de Dorian, ce n'est pas OK de retourner tous les programmes à cause des programmes inactifs.  Je pense qu'il faut un autre stratégie que de se dire qu'on va retourner tous les programmes dont les programmes non éligibles.

2024-10-15 08:44 UTC, dolemoine commented
Question: 
suite à l'identification du bug par @ttdm, est-ce qu'on pourrait imaginer une PR partielle avec uniquement les modifs sur le getOneProgram, qu'on appellerait à partir du moment où on se rend sur la page détail du program (peut-être uniquement depuis le catalogue dans un premier temps ?). 
On ne modifierait donc pas le comportement du get all sur la liste, mais on récupère la bonne info sur l'éligibilité sur le détails?
Je suis d'avis qu'on se fasse un point en visio sur ce sujet

2024-10-15 13:59 UTC, dolemoine commented
Note: 
- La différence sur le nombre de résultats sur le catalogue vient du fait que dans la version initiale du code, on retourne uniquement les programs qui passent la vérification `shouldKeepProgram` donc avec un retour d'évaluation à `true` ou `undefined`, les résultats à `false` étant exclus.
- Dans notre version, la fonction `shouldKeepProgram` retourn toujours `true` quand on est sur le catalogue, retournant donc également les 13 résultats pour lesquels l'évaluation retourne `false`. 

Question : Quel est le comportement attendu ? Il me semble que le résultat actuel sur le catalogue n'est pas le bon.

2024-10-15 14:54 UTC, ttdm commented
A ma connaissance, le comportement actuel est attendu, c'est pour ça que dans les stats, on a bien nombre de programme en prod = nombre de programmes sur le catalogue et nombre totla de programme = nombre de fichiers yamls. 

je suis forcément Ok pour séparer les PR, puisque la partie dont je dépend est fonctionnelle par contre ça ne règle pas ton problème =/
Je suis aussi OK pour en discuter; demain en début de journée ?

2024-10-15 15:06 UTC, dolemoine commented
OK pour split la PR -> 1 getPrograms et 1 getOneProgram, on peut en discuter demain matin oui

2024-10-17 10:41 UTC, yvalentin requested changes

2024-10-17 10:41 UTC, yvalentin commented on libs/backend-ddd/src/program/domain/programFeatures.ts
> +    const filterResult = this.filterProgramsArray(questionnaireData, [program])
todo: refactoriser le contenu de la boucle dans `filterPrograms`(libs/backend-ddd/src/program/domain/filterPrograms.ts:20)

2024-10-22 18:02 UTC, yvalentin approved these changes

2024-10-25 13:54 UTC, yvalentin commented
@dolemoine @ttdm Est-ce que cette branche devrait être plutôt être merge dans `release/siret-cross-recording` au lieu de `main` ?

2024-10-28 07:56 UTC, dolemoine commented
Il me semble que c'est bien dans `main` que cette branche doit être merge car @ttdm en a besoin pour une autre PR qui ne dépend pas de la feature enregistrement Siret

2024-10-28 08:02 UTC, ttdm commented
Je confirme c'est bien dans main. je peux merge ? @yvalentin

2024-10-28 08:16 UTC, ttdm commented on libs/backend-ddd/src/program/application/programService.ts
> +  public getOneMaybeWithEligibility(id: string, questionnaireData: QuestionnaireData): Result<ProgramTypeWithEligibility, Error> {
@dolemoine C'est une PR commune, n'hésite pas à faire la modif toi même !
Et c'est bien le second cas ;)

2024-10-28 08:19 UTC, yvalentin commented
> Je confirme c'est bien dans main. je peux merge ? @yvalentin

yep yep

2024-10-28 10:27 UTC, merged