docs: add contributors core team
betagouv/mission-transition-ecologique pull request #1253
Opened 2024-10-28 14:29 UTC by yvalentin

Dites moi si vous voulez changer quelques choses

2024-10-28 16:14 UTC, oumeimaelisbihani approved these changes

2024-10-28 16:25 UTC, ttdm approved these changes

2024-10-28 20:04 UTC, dolemoine requested changes

2024-10-28 20:04 UTC, dolemoine commented on README.md
> +    - [Dorian Lemoine](https://dorianlemoine.fr)
```suggestion
    - [Dorian Lemoine](https://github.com/dolemoine)
```

2024-10-28 20:04 UTC, dolemoine commented on package.json
> +    "Dorian Lemoine (https://dorianlemoine.fr)",
```suggestion
    "Dorian Lemoine (https://github.com/dolemoine)",
```

2024-10-31 09:00 UTC, dolemoine approved these changes

2024-11-04 09:10 UTC, merged