Feature : Enregistrement manuel dans la modale avec choix d'une ville et non d'une région
betagouv/mission-transition-ecologique pull request #1284
Opened 2024-11-06 14:22 UTC by oumeimaelisbihani

- Utilisation de l'api https://geo.api.gouv.fr/ avec la création d'une LocalisationApi
- Modification du composant TeeProfileLocalisation

2024-11-08 12:39 UTC, ttdm commented
Suite à nos discussions d'hier sur l'utilisation d'un fichier texte vs api, je me suis supprimé de la review. 
Je te laisse me retag/nous retag avec dorian quand ce sera ok.

2024-11-19 15:33 UTC, dolemoine commented on libs/backend-ddd/src/geoSearch/application/geoSearchService.ts
> +import { communes } from '@tee/data/references'
Praise: top cette classe de service et ses logiques

2024-11-19 15:34 UTC, dolemoine commented on libs/backend-ddd/src/geoSearch/application/geoSearchService.ts
> +  public separateCitiesByPostalCode(): ConvertedCommune[] {
suggestion: passer cette méthode en privée (elle semble utilisée uniquement dans cette classe)

2024-11-19 15:38 UTC, dolemoine commented on apps/web/src/utils/storage/companyDataStorage.ts
> +  static getSiretBasedCompanyData(
praise: top la gestion des deux cas de figures pour l'origine des données

2024-12-02 11:23 UTC, yvalentin requested changes

2024-12-02 11:23 UTC, yvalentin commented on libs/backend-ddd/src/geoSearch/application/geoSearchService.ts
> +    const normalizeString = (str: string) =>
suggestion: ajouter un commentaire pour expliquer le normalisation. Il est aussi possible de le sortir dans une fonction private

2024-12-02 11:23 UTC, yvalentin commented on libs/backend-ddd/src/geoSearch/application/geoSearchService.ts
> +export default class GeoSearchService {
todo: mettre en place une archi plus `ddd` comme discuter à l'orale

2024-12-02 11:23 UTC, yvalentin commented on apps/web/src/components/identification/details/TeeProfileSize.vue
> +    v-if="!infos.value"
suggestion: avoir une methode hasError qui reprend la condition du if dans le errorMessage

if (!props.infos.value && props.showError) {

2024-12-10 14:58 UTC, oumeimaelisbihani commented
@yvalentin pour une validation fonctionnelle les fix de l'enregistrement manuel de @dolemoine ont été ajoutés à cette feature la ici : https://github.com/betagouv/mission-transition-ecologique/pull/1421

2024-12-11 14:40 UTC, yvalentin approved these changes
review fait en pair

2024-12-24 14:33 UTC, dolemoine approved these changes

2024-12-26 10:03 UTC, merged