premièr proposition page budget
betagouv/mission-transition-ecologique pull request #1312
Opened 2024-11-14 15:38 UTC by ttdm

Proposition d'une page budget

2024-11-18 15:58 UTC, oumeimaelisbihani requested changes
un request changes juste pour au moins les données du tableau, le reste c'est pas obligé

2024-11-18 15:58 UTC, oumeimaelisbihani commented on apps/web/src/pages/TeeBudgetPage.vue
> +      <div class="fr-col-12 fr-col-lg-7 fr-col--middle fr-col-justify--center">
[suggestion] : avoir la data pas en dur mais plutot en variable dans la partie script

2024-11-18 15:58 UTC, oumeimaelisbihani commented on apps/web/src/pages/TeeBudgetPage.vue
> +      <li>
[suggestion] : peut etre pareil que pour le tableau avoir un tableau de liens/noms pour en rajouter assez facilement si nécessaire ?

2024-11-22 08:06 UTC, ttdm commented on apps/web/src/pages/TeeBudgetPage.vue
> +      <div class="fr-col-12 fr-col-lg-7 fr-col--middle fr-col-justify--center">
(petite remarque, pour la clarté de la lecture de la review ceci n'est pas une suggestion mais un "request change" ;) )

2024-11-22 08:06 UTC, ttdm commented on apps/web/src/pages/TeeBudgetPage.vue
> +      <li>
Ici ce n'est pas si trivial, par exemple avec la ligne ou il y a 3liens vs les 4 autres lignes qui sont des liens simples

2024-11-22 09:27 UTC, ttdm commented
J'ai une demande de mise en prod en urgence de JB. 
Comme on est sur une feature bien identifiée, séparée du reste du site et après discussion avec Dorian, j'envoi en prod et on fera les modifs sur une nouvelle PR.

2024-11-22 09:31 UTC, merged