Feat: Choix du secteur d'activités dans la modale d'enregistrement des informations de l'entreprise
betagouv/mission-transition-ecologique pull request #1335
Opened 2024-11-21 15:35 UTC by oumeimaelisbihani

* utilisation du fichier json nafMapping 
* ajout de la fonction de search dans le fichier renommé nafJSONsearch
* modification du composant TeeProfileActivity > possibilité de chercher par naf, naf1, secteur
* ajout des informations dans la structure de données sauvegardées en manuel ou basée sur le siret

2024-12-02 23:59 UTC, ttdm requested changes
TODO : Propager le changement dans "je complète manuellement mes infos"

et 2,3 points bloquants détaillés aux endroits dédiés dans le code. 

Beau travail sur le composant front !

2024-12-02 23:59 UTC, ttdm commented on apps/backend/src/controller/establishment/establishmentController.ts
> +    @Query() searchTerm: string,
Mini remarque : "term" pourrait laisser croire que c'est forcément un mot. 
propositions : queryText / searchQuery / searchInput

2024-12-02 23:59 UTC, ttdm commented on apps/web/src/assets/scss/input.scss
Petite question : tu as vérifié qu'il n'y avait pas de side effect ? 
(Oui je sais, je pose toujours la même question quand un fichier global est modifié x) )

2024-12-02 23:59 UTC, ttdm commented on apps/web/src/components/identification/details/TeeProfileActivity.vue
> +      :class="errorMsg ? 'fr-input-group--error' : 'fr-input-group--valid'"
Praise: nice le visuel du message d'erreur

2024-12-02 23:59 UTC, ttdm commented on apps/web/src/components/identification/details/TeeProfileActivity.vue
Praise pour tout le composant !

2024-12-02 23:59 UTC, ttdm commented on apps/web/src/components/identification/details/TeeProfileActivity.vue
> +        :key="`resp-input-${activity.codeNAF}-${activity.codeNAF1}`"
Question: "resp-input-${activity.codeNAF}" pose problème ?

2024-12-02 23:59 UTC, ttdm commented on apps/web/src/components/identification/details/TeeProfileActivity.vue
> +})
Remarque : comme c'est une query interne pas très lourde, je pense que c'est un des rares cas où ça n'est pas nécessaire. 
(A confirmer)

Je suggère de supprimer ou de réduire à 100ms.

2024-12-02 23:59 UTC, ttdm commented on apps/web/src/components/identification/details/TeeProfileActivity.vue
> +    class="fr-tag fr-mb-4v fr-bg--blue-france--lightness"
Il y a une marge bottom en trop; je pense que ça vient d'ici.

2024-12-02 23:59 UTC, ttdm commented on apps/web/src/components/identification/details/TeeProfileDetails.vue
> +    value: props.company ? { secteur: props.company.secteur, codeNAF: props.company.codeNAF, codeNAF1: props.company.codeNAF1 } : undefined,
Question: y a t'il un intéret spécifique à stocker chacune de ces données ? Le codeNAf contient la totalité des infos. C'est pour de l'utilisation à certains endroits sans avoir à refaire une query sur le NAF ? 

C'est pour être sur de bien comprendre.
Je pense que je suis OK le code actuel que je vois comme plus pratique pour un cout très faible.

2024-12-02 23:59 UTC, ttdm commented on apps/web/src/service/api/establishmentApi.ts
> +    const urlWithParams = `${this.url}searchNAF?searchTerm=${encodeURIComponent(query)}`
TODO : Il faudrait éviter de se retrouver avec un nom de variable en dur. 
Sachant qu'il n'y a qu'un seul paramère, je me demande si c'est possible d'avoir 
const urlWithParams = `${this.url}searchNAF?${encodeURIComponent(query)}` 
et dans le backend 
 @Get('/searchNAF?{query}')
  public getOne(
    @Path() query: string,
  

Sinon il faudrait créer une interface dans la librarie common.

2024-12-02 23:59 UTC, ttdm commented on libs/common/src/establishment/types.ts
> +}
Remarque : je suis étonné d'avoir des undefined dans ce type. 
Si nécessaire, il me semble mieux de toujours avoir les valeurs mais d'avoir le code, la où c'est utilisé dans le code CompanyActivityType | undefined

2024-12-02 23:59 UTC, ttdm commented on libs/backend-ddd/src/establishment/infrastructure/json/nafJsonSearch.ts
Reste à review. Je te laisse avec mes autres commentaires pour démarrer !

2024-12-09 16:49 UTC, oumeimaelisbihani commented on apps/web/src/components/identification/details/TeeProfileDetails.vue
> +    value: props.company ? { secteur: props.company.secteur, codeNAF: props.company.codeNAF, codeNAF1: props.company.codeNAF1 } : undefined,
c'est pour avoir le même niveau de données que l'enregistrement avec Siret

2024-12-10 16:02 UTC, oumeimaelisbihani commented on apps/web/src/components/identification/details/TeeProfileActivity.vue
> +    class="fr-tag fr-mb-4v fr-bg--blue-france--lightness"
non c'est pour éviter l'effet bizarre de tressautement à l'affichage des messages d'erreur

2024-12-10 16:03 UTC, oumeimaelisbihani commented on apps/web/src/components/identification/details/TeeProfileActivity.vue
> +        :key="`resp-input-${activity.codeNAF}-${activity.codeNAF1}`"
oui parce qu'il peut y avoir deux meme code NAF

2025-01-08 13:37 UTC, ttdm commented
Salut, j'ai vu que tu as répondu à la majorité de mes remarques précédentes. 
Par contre, et c'est la même chose pour toutes nos PR actuelles, on va devoir les passer sous nuxt. 
Du coup ce que je te propose c'est de migrer ce code sous nuxt dès que possible. 
Puis je repasserai dessus. 
Si tu veux, pour se répartir le travail, tu peux t'économiser le temps de refaire une review fonctionnelle approfondie et je la ferai moi.

2025-01-13 14:51 UTC, closed without merging