feat: Add company data filter to program listing
betagouv/mission-transition-ecologique pull request #1400
Opened 2024-12-05 22:18 UTC by dolemoine

Introduced a new company data filter to improve the customization of program listings based on selected company attributes. The filter integration enables toggling visibility and selection of programs through company-specific criteria, enhancing user navigation and interaction within the program catalog. Modifications include updates to related components, data handling, and eligibility checks to align with the new filter functionality.

2024-12-16 23:52 UTC, ttdm requested changes
Remarque : Dans le ticket référencé, il faut signaler à JB et coline que le point suivant  n'est pas traité dans le reste du ticket (s'ils veulent créer une autre carte sur ce point): 
"En tant qu'entreprise, j'arrive sur une fiche aide depuis une recherche google, je m'identifie depuis la fiche aide et m'aperçois que je ne suis pas éligible à cette aide. Un CTA "voir mes aides éligibles" m'amène sur le catalogue des aides filtrées pour mon entreprise. "

Praise ++ sur le rendu vraiment très sympa ! 

Je ne reviens sur la petite remarque sur le tag effectif que je t'ai fait en direct. 
J'ai par contre un autre point en bloquant : le filtre d'entreprise que tu as ajouté est visible et présent dans le résultat par aide du parcours je ne sais pas par ou commencer. Je pense que ce n'est pas voulu.

2024-12-18 22:34 UTC, dolemoine commented on apps/web/src/stores/program.ts
>    const programFilters = ref<programFiltersType>({
je ne comprends pas ta suggestion :smile:

2024-12-18 22:40 UTC, dolemoine commented
Réponse à tes commentaires généraux sur la PR : 

> Remarque : Dans le ticket référencé, il faut signaler à JB et coline que le point suivant n'est pas traité dans le reste du ticket (s'ils veulent créer une autre carte sur ce point):
"En tant qu'entreprise, j'arrive sur une fiche aide depuis une recherche google, je m'identifie depuis la fiche aide et m'aperçois que je ne suis pas éligible à cette aide. Un CTA "voir mes aides éligibles" m'amène sur le catalogue des aides filtrées pour mon entreprise. "

Bien vu, j'ai réactivé le CTA (qui était présent mais commenté comme le filtrage n'était pas fonctionnel)

> J'ai par contre un autre point en bloquant : le filtre d'entreprise que tu as ajouté est visible et présent dans le résultat par aide du parcours je ne sais pas par ou commencer. Je pense que ce n'est pas voulu.

Ça a été vu avec Coline, on le laisse bien présent, j'ai juste fait une petite adaptation pour que le checkbox soit disable sur le parcours (il n'y a effectivement pas d'intérêt de proposer le choix sur le filtrage des résultats avec les données d'entreprise)

2024-12-18 22:42 UTC, dolemoine commented on apps/web/src/stores/program.ts
> +    [FilterItemKeys.companyData]: false
Bonne question, il me semble que je l'avais ajouté car j'avais besoin à un moment donné de vérifier qu'une key passée en param était bien un des enum, mais en revoyant le code je me dis que je peux probablement revenir à la version précédente.

2024-12-18 22:50 UTC, ttdm commented on apps/web/src/stores/program.ts
>    const programFilters = ref<programFiltersType>({
Hmm, elle est pas au bonne endroit, quand on réfère sur une ligne qui n'a pas changé, j'ai l'impression que ça ne fonctionne jamais proprement. 

`  const programFilters = ref<programFiltersType>({` -> ` const programFilters = ref<ProgramFiltersType>({`

2024-12-18 22:51 UTC, ttdm commented on apps/web/src/stores/program.ts
> +    [FilterItemKeys.companyData]: false
@yvalentin en deuxième review pour voir ce que lui en pense ;)

2024-12-18 22:52 UTC, ttdm commented
Du coup pour moi, tu as répondu à mon point bloquant donc c'est bon. 
Je signale que je n'ai PAS refait de revue fonctionnelle. "Je n'ai PAS revérifié que tes modifs n'apportaient pas de regressions"

2024-12-18 22:52 UTC, ttdm approved these changes

2024-12-18 22:53 UTC, dolemoine commented on apps/web/src/stores/program.ts
>    const programFilters = ref<programFiltersType>({
ok c'est traité

2024-12-18 22:54 UTC, dolemoine commented
J'ai refait une passe fonctionnelle de mon côté, coté catalogue ET parcours "je ne sais pas par où commencer", pas de regressions identifiées

2025-01-02 09:33 UTC, yvalentin commented
Je suppose qu'il faut plutôt regarder la PR suivante maintenant ?
https://github.com/betagouv/mission-transition-ecologique/pull/1464

2025-01-14 15:35 UTC, closed without merging