Feat/siret catalog impact nuxt
betagouv/mission-transition-ecologique pull request #1464
Opened 2024-12-24 14:50 UTC by dolemoine

2024-12-30 15:49 UTC, oumeimaelisbihani approved these changes
Nickel l'adaptation à nuxt, j'ai juste vérifié ça comme la feature avait été revue dans la #1400 ! Par contre un retour fonctionnel juste sur le temps de réaction entre le moment où on désactive le filtre puis on le réactive, ça met un certain temps. Est ce qu'on pourrait rajouter un loader ?

2025-01-13 15:23 UTC, yvalentin requested changes
Trop cool comme fonctionnalité !

J'aimerais pouvoir échangé sur la manière d'avoir les data en fonction de si c'est coché ou pas et du `ProgramEligibility`

Je te laisse revenir vers moi

2025-01-13 15:23 UTC, yvalentin commented on apps/nuxt/src/stores/program.ts
> +    } else if (filterKey === FilterItemKeys.companyData) {
todo: remplacer par un `if`

comme le if précédent à un `return` le `else if` est inutile

2025-01-13 15:23 UTC, yvalentin commented on apps/nuxt/src/components/program/list/filters/ProgramFiltersAccordion.vue
> +        :class="[props.accordionClass, filter.accordionClass, companyDataFilterVisibilityClass(filter.id)]"
todo: il semblerais que `companyDataFilterVisibilityClass(filter.id)` ne sert à rien ici ??

En plus, pourquoi faire un `hidden` s'il y a djà un `if` ?

2025-01-13 15:23 UTC, yvalentin commented on apps/nuxt/src/components/program/list/filters/ProgramFiltersAccordion.vue
> +      :class="[props.accordionClass, companyDataFilterVisibilityClass(companyDataFilter.id)]"
todo: la fonction `companyDataFilterVisibilityClass(companyDataFilter.id)` renvoie un hidden ou pas... Il est peut être plus pertinant d'utiliser le `if` qui est sur l'accordéon group `v-if="companyDataFilter.display"`

```ts
const companyDataFilter: FilterItem = {
  title: 'Entreprise',
  id: FilterItemKeys.companyData,
  component: ProgramFilterByCompanyData,
  componentClass: 'fr-pl-2v',
  display: CompanyData.isDataFull().value
}
```

2025-01-15 10:22 UTC, dolemoine commented on apps/nuxt/src/components/program/list/filters/ProgramFiltersAccordion.vue
> +        :class="[props.accordionClass, filter.accordionClass, companyDataFilterVisibilityClass(filter.id)]"
oui c'est un oubli, c'est effectivement obsolète

2025-01-15 10:34 UTC, dolemoine commented
@yvalentin j'ai apporté l'ensemble des changements évoqués dans tes remarques. On se parle de ça quand tu veux :

> J'aimerais pouvoir échangé sur la manière d'avoir les data en fonction de si c'est coché ou pas et du `ProgramEligibility`

2025-01-15 15:07 UTC, yvalentin approved these changes

2025-01-17 10:11 UTC, merged