feat: add TeeDsfrTags. Filter objective with TeeDsfrTags
betagouv/mission-transition-ecologique pull request #688
Opened 2024-04-11 20:20 UTC by yvalentin

2024-05-13 22:33 UTC, ttdm requested changes
Comme d'hab, le code est super propre ! 

Il y a par contre quelques petits changements fonctionnels nécessaires avant merge : 
- [ ] sur téléphone, les marges extérieures ont sautées sur tous les affichages de résultats.
- [ ] il manque 16 programmes dans l'annuaire, 7 dans la catégorie déchets et 9 dans mobilité. A priori, les filtres fonctionnent, dans les autres parcours, je n'ai pas réussi à avoir de différences entre la prod et ta branche en faisant plusieurs tests. Je viens de finir par la revue fonctionnelle et je n'ai pas le temps de chercher ce qui peut causer ce problème. Désolé de te le laisser sans plus d'aide.

Dans le code, j'ai fait quelques remarques/suggestions qui sont plus de l'archi et qui permettent d'illustrer les discussions qu'on a eu ces dernières semaines. Rien de nécessaire.

Je note quand même ici que j'ai commencé à 18h et qu'il est minuit passé, j'ai accéléré à la fin + j'étais fatigué donc je peux vraiment avoir laisser passé des trucs. C'était soit ça soit pas de review avant mercredi aprèm.

2024-05-13 22:33 UTC, ttdm commented on packages/web/src/components/program/list/ProgramList.vue
> +          radius-size="2-5v"
Suggestion: ces propriétés pourrait être combinées et remplacées par un props "type"=progamList qui englobe les deux options à la fois.

2024-05-14 09:28 UTC, oumeimaelisbihani commented on packages/common/src/questionnaire/objectiveChecker.ts
> +  static isEcoDesign(wastesMaterials: YesNo) {
question : je n'ai pas réussi à comprendre pourquoi on vérifie le statut Unknown seulement pour certains objectifs

2024-05-14 09:32 UTC, oumeimaelisbihani reviewed
Très lisible et propre ! J'ai juste ajouté une question dans l'ObjectiveChecker mais sinon rien de plus à ajouter par rapport à @ttdm

2024-05-14 10:15 UTC, ttdm commented on packages/common/src/questionnaire/objectiveChecker.ts
> +  static isEcoDesign(wastesMaterials: YesNo) {
Globalement, l'idée est de savoir quels programmes on conserve dans les résultats à partir des réponses de l'utilisateur. 

Le filtrage conserve tous les programmes pour lesquels au moins un des objectifs du programme est recherché par l'utilisateur. 

Le choix a été fait par l'équipe d'être le plus large possible sur les objectifs de l'utilisateur donc tous les objectifs vérifiés par l'objective checker sont mis à Yes si la réponse n'est pas directement négative. 

Les deux fois ou on vérifie unknown c'est qu'il y a deux réponses à mettre à Oui et deux réponses à mettre à Non donc autant dire qu'on met à Oui tous les cas à mettre à Oui donc Oui et Unknown.

2024-05-15 08:16 UTC, ttdm approved these changes

2024-05-15 12:23 UTC, merged