Feat/form field validator
betagouv/mission-transition-ecologique pull request #736
Opened 2024-05-15 12:55 UTC by dolemoine

- refacto de l'interface OppoturnityFormType
> - ajout de types pour gérer la répétition du typage des propriétés (DefaultFieldInputType, StringFieldInputType, BooleanFieldInputType et ValidatedStringFieldInputType)
> - ajout des propriétés validation, errorMessage et isValid pour gérer la validation de certains champs (email, tel, SIRET)
-  refacto de la classe Validator en SiretValidator et création de deux nouveaux validator pour email et tel (validation via regex)
- modification du composant vue ProgramForm
> -  implémentation des modifications de l'interface OpportunityFormType dans le composant vue ProgramForm via l'initialisation des propriétés nouvellements créées
> - ajout étape de validation des champs email, tel et SIRET contraignant l'envoi des données
> - implémentation du message d'erreur pour informer l'utilisateur d'une validation en erreur

2024-05-15 20:49 UTC, yvalentin requested changes
Les autres points ont été discuté en pair review

2024-05-16 06:24 UTC, dolemoine commented on packages/web/src/utils/validator/siretValidator.ts
> +export default class SiretValidator {
point traité via le commit [c93c530](https://github.com/betagouv/mission-transition-ecologique/pull/736/commits/c93c5301a06a56103e211da9781631c1da522de3)

2024-05-16 20:10 UTC, yvalentin commented
Je remet la PR en draft et l’enlève de la review afin que le point sur la stratégie de validation soit mise en place

2024-05-23 20:36 UTC, yvalentin requested changes
question: en terme de comportement pour les champs email et téléphone, je m'attendrais à avoir un message d'erreur `ce champs est obligatoire`, non ? c'est peut être voulu ?

![image](https://github.com/betagouv/mission-transition-ecologique/assets/1521862/dd4e3a23-cad9-4ebd-a603-9c5371609e5b)

2024-05-23 20:36 UTC, yvalentin commented on packages/web/src/components/program/detail/ProgramForm.vue
> +    else field.isValid = field.validation(field.value) as boolean
todo: ajouter les parenthèse pour faciliter la lisibilité

Pour info, je vais ajouter la règle suivant à `all` qui permettra d'avoir des remontées d'erreurs automatiquement
https://eslint.org/docs/latest/rules/curly

2024-05-23 20:36 UTC, yvalentin commented on packages/web/src/types/opportunityFormType.ts
> +  field: StringFieldInputType | MandatoryStringFieldFormType | BooleanFieldInputType | ValidatedStringFieldInputType
todo: il doit être possible d'utiliser le type `InputFieldUnionType` directement à la place de `StringFieldInputType | MandatoryStringFieldFormType | BooleanFieldInputType | ValidatedStringFieldInputType`

2024-05-23 20:36 UTC, yvalentin commented on packages/web/src/utils/validator/siretValidator.ts
> +
todo: oui effectivement utilisé le validator qui dans `common`

2024-05-23 20:36 UTC, yvalentin commented on packages/web/src/utils/validator/emailValidator.ts
> +  static readonly validate = (email: string): boolean => {
todo: dans les validators `EmailValidator` et `PhoneValidator` la valeur peut être à `undefined`

Ici, une erreur est jeté dans le validator du phone à cause du `replace` sur `undefined`

Ajouter la condition suivante
```
if (!phone) {
  return false
}

2024-05-23 20:36 UTC, yvalentin commented on packages/web/src/components/program/detail/ProgramForm.vue
> +:deep(.fr-valid-text:before) {
praise: j'avais pas notion des fonctions vue comme `:deep` ou  `:slotted` ! Cool !

2024-05-23 20:36 UTC, yvalentin commented on packages/web/src/components/program/detail/ProgramForm.vue
> +}
todo: si c'est le display voulu pour les inputs valide, le `scss` pourrait être dans le dossier `assets`

2024-05-27 08:21 UTC, dolemoine commented
> question: en terme de comportement pour les champs email et téléphone, je m'attendrais à avoir un message d'erreur `ce champs est obligatoire`, non ? c'est peut être voulu ?
> 
> ![image](https://private-user-images.githubusercontent.com/1521862/333332874-dd4e3a23-cad9-4ebd-a603-9c5371609e5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3OTU0NjQsIm5iZiI6MTcxNjc5NTE2NCwicGF0aCI6Ii8xNTIxODYyLzMzMzMzMjg3NC1kZDRlM2EyMy1jYWQ5LTRlYmQtYTYwMy05YzUzNzE2MDllNWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjdUMDczMjQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWViODgyM2UzOTU0ZjE0MjIwZjY5Yjc5YzliNWJjNTkwMDlhNjE1OGJiNjA0ZThlYTRiN2NkZGU4YTJiYTVjZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2WdvNugxnDWBUz--i4-7Mbds8Qyc-jQ2tZQN6RRSm68)

Sur ce point j'attends la confirmation mais la validation côté fonctionnelle avait déjà été faite .

2024-05-29 09:10 UTC, yvalentin approved these changes

2024-05-29 14:38 UTC, merged