Feat/create json files from baserows
betagouv/mission-transition-ecologique pull request #821
Opened 2024-06-10 20:32 UTC by ttdm

draft, 

close #796
close #803
close #804
close #805

2024-06-26 14:40 UTC, yvalentin requested changes
Praise: Gros boulot ! Bravo !

Je t'ai fait pas mal de retour... Mais beaucoup de mineur ;-) Et c'est propre ! Merci

2024-06-26 14:40 UTC, yvalentin commented on packages/data/src/projects/baserows.ts
> +      return 'plan-transition-bas-carbone.webp'
question: Pourquoi une valeur par défaut ? Pourquoi celle-ci ? On est sur quelle va exister ?

Pourrait-on la mettre en constant au début de la classe `defaultImageName` ?

2024-06-26 14:40 UTC, yvalentin commented on packages/data/src/projects/project.ts
> +  private _resetImageFolder() {
praise: super pour le reset du folder de la partie front !

2024-06-26 14:40 UTC, yvalentin commented on packages/data/src/projects/baserows.ts
> +    return programs.map((value) => {
todo: renommer `value` en `program`

2024-06-26 14:40 UTC, yvalentin commented on packages/data/src/projects/baserows.ts
> +    return projects.map((value) => {
todo: rename `value` en `project`

2024-06-26 14:40 UTC, yvalentin commented on packages/data/src/projects/baserows.ts
> +    secondaryThemes.forEach((element) => {
todo: rename `element` en `secondaryTheme` ou `theme`

2024-06-26 14:40 UTC, yvalentin commented on packages/data/src/projects/baserows.ts
> +        console.warn('theme not found in baserow data (should not happen!)')
note: peut être ajouter dans le warn (car c'est le même que la ligne 137) `from generateThemeList` | `from generateMainTheme`

2024-06-26 14:40 UTC, yvalentin commented on packages/data/src/projects/project.ts
> +    project.themes.forEach((themeId) => {
suggestion: sur les trois méthodes `_validateThemes`, `_validateLinkedProjects` et `_validatePrograms`, on pourrait passer directement les valeurs utiliser dans le foreach

ex:

```ts
this._validateThemes(project.themes)
...
private _validateThemes(themes: string[]) {
...
```

2024-06-26 14:40 UTC, yvalentin commented on packages/data/src/projects/project.ts
> +      const projectFound = rawProjects.some((proj) => proj.id === projectId)
suggestion: remplacer `proj` par `project` (car on peux passer directement les `linkedProjects`) ou `rawProject`

2024-07-01 16:16 UTC, ttdm commented on packages/data/src/projects/baserows.ts
> +    const imageId = baserowImage[0].id
https://stackoverflow.com/questions/4090491/how-to-get-the-first-element-of-an-array

2024-07-01 16:21 UTC, ttdm commented on packages/data/src/projects/project.ts
> +    return
j'ai ajouté des sauts de ligne mais je ne suis pas sur de la où il faut en mettre exactement. 
Ex :   

```
private async _delay(ms: number): Promise<void> {
    return new Promise((resolve) => setTimeout(resolve, ms))
  }
```

vs 

```
  private async _delay(ms: number): Promise<void> {
    console.log(xxx)
    return new Promise((resolve) => setTimeout(resolve, ms))
  }
```

2024-07-01 16:27 UTC, ttdm commented on packages/data/src/projects/project.ts
> +    project.themes.forEach((themeId) => {
Je pensais aussi mais comme on fait d'abord tous les téléchargements puis toutes les validations, il y a besoin de donner tout le projet en paramètre pour pouvoir afficher son titre et son id en cas de problème.

2024-07-04 12:30 UTC, merged