Feat: add project result page
betagouv/mission-transition-ecologique pull request #841
Opened 2024-06-19 14:32 UTC by dolemoine

refacto de la page résultats

- refacto du component ProgramList pour les réduires à la simple liste 
- création d'un component CatalogList utilisé pour l'annuaire et intégration 
- création d'un component ProjectList mettant en avant la liste des projets relatifs aux 
- création d'un component ResultList intégrant le système de DsfrTabs pour gérer l'affichage des résultats par projets et par aides diponibles (intégrant les components ResultProjectList 
- ajout des styles custom pour gérer la disposition des tabs, des project cards...

refacto des 

- ajout d'une méthode générique get() dans la classe requestApi et refacto des classes api qui l'étende
- ajout d'un projectApi (utilisant pour le moment les données statiques des projets)

2024-07-10 13:23 UTC, ttdm requested changes
Comme discuté en visio, il y a quelques changements nécessaires; en particulier sur les filtres.

Praise : Gros travail de refacto très efficace sur un grosse partie de la PR. 

Pour info, Je suis en review depuis 10h du mat et je dois dire que j'ai un peu saturé sur la fin, notamment sur les gros fichiers où il y a énormément de lignes de spacing. 
Je n'ai fais qu'une remarque ou deux mais je suis vraiment persuadé que tu dois pouvoir faire du spacing plus clair. Si je devais faire une remarque général sur un point d'amélioration ce serait ça. 
Sur le reste, et notamment sur la partie sur laquelle tu as passé du temps à refacto, c'est vraiment clean :)

2024-07-10 13:23 UTC, ttdm commented on apps/web/src/utils/project/projectFilters.ts
> +    return true
Cette valeur par défaut me parait douteuse. 
Elle peut cacher une/des erreurs. 
A priori, on ne doit jamais être ici. Peut être au minimum logger quelque chose via sentry ?

2024-07-10 13:23 UTC, ttdm commented on apps/web/src/config.ts
>    }
A priori baseUrl n'est utilisé nulle par dans le front. 
Ca ne serait pas possible de ne pas avoir de baseUrl et de modifier deployUrl entre nos .env de dev et de prod ?

2024-07-10 13:23 UTC, ttdm commented on apps/web/src/components/project/list/ProjectList.vue
> +  </div>
ça m'étonne que ça ne puisse pas être plus simple. 
Il y a 4divs de spacing pour un unique composant.

2024-07-10 13:23 UTC, ttdm commented on apps/web/src/components/project/list/ProjectList.vue
> +  <!--  LIST OF PROJECT CARDS-->
pour info ce commentaire n'est pas cohérent avec le suivant ( même écriture de commentaire mais pas même chose décrite)

2024-07-10 13:23 UTC, ttdm commented on apps/web/src/components/project/list/ProjectList.vue
> +                  Voici les actions par lesquelles commencer pour votre TPE du secteur Hôtels et hébergement similaire :
A changer !

2024-07-10 13:23 UTC, ttdm commented on apps/web/src/components/project/list/ProjectList.vue
> +    v-if="hasPriorityProjects && !hasObjectiveCard && !hasObjectiveSelected"
C'est peut être pas possible mais si possible, ce serait un plus d'unifier ce v-if avec celui du dessus qui a la même condition

2024-07-10 13:23 UTC, ttdm commented on apps/web/src/components/project/list/ProjectList.vue
> +          <div class="fr-grid-row fr-grid-row--gutters fr-grid-row--center fr-grid-row-md--left">
même remarque que plus haut, je trouve ça étonnant d'enchainer 4 divs de spacing (même 5 en comptant les classes dans la div du v-if !). N'y a t'il pas plus simple ?

2024-07-11 07:48 UTC, dolemoine commented on apps/web/src/assets/scss/router.scss
Pour le coup j'ai gardé cette modif venant du push pré démo (mix du boulot entre oumeima et moi sur les projets), je peux virer cette partie et vérifier qu'oumeima a gérer ça de son côté (peut-être différemment ?)

2024-07-11 08:12 UTC, dolemoine commented on apps/web/src/components/questionnaire/result/list/ResultListNoResults.vue
> +    />
Indeed, code legacy, j'ai pas retouché cette partie

2024-07-11 08:18 UTC, dolemoine commented on apps/web/src/assets/scss/grid.scss
> +
L'idée ici c'est surtout de pouvoir gérer un alignement pour chaque breakpoint, ce que ne semble pas proposer le dsfr (recherche faite sur la lib dsfr dans le projet), ex : fr-grid-row-md--center pour gérer le centrage du contenu à partir du breakpoint md

2024-07-11 08:32 UTC, dolemoine commented on apps/web/src/assets/scss/typography.scss
> +}
Non c'est une création, le dsfr ne semble pas proposer de classe permettant de gérer le style de typo (le passage en italic est fait en dur : `font-style: italic`

2024-07-11 09:03 UTC, dolemoine commented on apps/web/src/assets/scss/background.scss
> +        @include backgroundColor($properties, -75%);
Du coup j'ai du créer une seconde mixin pour gerer l'itération sur une liste défini en début de fichier contenant le nom de la class appliquée (light ou lightness) et sa value. 

Je trouve ça plus propre.

2024-07-11 09:06 UTC, dolemoine commented on apps/web/src/components/catalog/CatalogList.vue
> +      </div>
En principe cette partie est déjà dans main, c'est une issue qui a été validée précédement.
Mais ça vaut surement le coup de garder une trace de ça pour faire cette modif.

2024-07-11 09:33 UTC, ttdm commented on apps/web/src/assets/scss/router.scss
SI c'était déjà présent, n'y touche pas forcément je pense ;) Surtout vu le timing de tes vacances :)

2024-07-11 09:34 UTC, ttdm commented on apps/web/src/assets/scss/typography.scss
> +}
Ok bonne idée, par contre je propose d'éviter un naming en fr- pour des éléments qui ne proviennent pas du dsfr.

2024-07-11 10:10 UTC, dolemoine commented on apps/web/src/components/project/list/ProjectList.vue
> +  </div>
j'ai virer un niveau sur cet élément

2024-07-11 10:16 UTC, dolemoine commented on apps/web/src/components/project/list/ProjectList.vue
> +                  Voici les actions par lesquelles commencer pour votre TPE du secteur Hôtels et hébergement similaire :
idem j'ai supprimé un niveau et j'ai rebase le v-if dans le premier niveau fr-grid-row pour éviter la div inutile du v-if.
mais globalement je vois mal comment réduire les 4 niveaux : 
- 1er niveau fr-grid-row gère une row globale au niveau du container-fluid parent (nécessaire par ex pour appliquer le bg--green--lightness) et baser le contenu sur toute la largeur et gère le centrage du contenu
- 2ème niveau fr-container -> bloque la largeur max du contenu sur la largeur container 
- 3ème niveau fr-col par ex -> gère le offset notamment, pour conserver le "bandeau" de gauche (là où on inclu l'image dans les projets prioritaires par ex)
- 4ème niveau fr-grid-row pour gérer l'agencement de la liste en elle même (qui est définie en fr-col)
j'ai fait quelques essaies mais je vois mal comment simplifier l'agencement des élements pour le moment, vu le temps imparti notamment...

2024-07-11 10:17 UTC, dolemoine commented on apps/web/src/components/project/list/ProjectList.vue
> +          <div class="fr-grid-row fr-grid-row--gutters fr-grid-row--center fr-grid-row-md--left">
même commentaire qu'au dessus

2024-07-11 17:47 UTC, ttdm commented on apps/web/src/components/project/list/ProjectList.vue
> +                  Voici les actions par lesquelles commencer pour votre TPE du secteur Hôtels et hébergement similaire :
Déjà désolé pour la brièveté de ce commentaire ! 

Le commentaire c'était pour le texte en dur !

2024-07-15 14:46 UTC, merged