fix: add undefined check in siretValidator
betagouv/mission-transition-ecologique pull request #848
Opened 2024-06-26 14:40 UTC by dolemoine

fix #823

2024-06-26 15:51 UTC, oumeimaelisbihani approved these changes

2024-06-27 07:52 UTC, yvalentin requested changes

2024-06-27 07:52 UTC, yvalentin commented on packages/common/src/establishment/validator/siretValidator.ts
>    static validate = (siret: string): boolean => {
todo: la méthode doit pouvoir accepter le `undefined`

```ts
static validate = (siret?: string): boolean => {
```

ps: ajouter un saut de ligne entre `}` et la `const` ;-)

2024-06-27 08:44 UTC, yvalentin approved these changes

2024-06-27 08:46 UTC, merged