Changement de la couleur Economies d'eau en bleu roi
betagouv/mission-transition-ecologique pull request #886
Opened 2024-07-15 14:12 UTC by oumeimaelisbihani

- Changement au niveau de la liste des themes pour la thématique Economies d'eau en Color.blueFrance
- Changement au niveau du fichier scss des cards pour accepter les couleurs qui n'ont pas la structure {background-color: "", color}

2024-07-17 10:06 UTC, yvalentin requested changes

2024-07-17 10:06 UTC, yvalentin commented on apps/web/src/assets/scss/card.scss
> +        color: white;
todo: ici si on veux mettre un color de texte en rapport avec un background, il faut le faire dans le setting des colors

```scss
...
"blue-france": (
    "background-color": color.$blue-france, // #000091
    "color": var(--text-inverted-blue-france),
    "is-inverted": true,
  ),
  ...
  ```

2024-07-17 14:52 UTC, oumeimaelisbihani commented on apps/web/src/assets/scss/card.scss
> +        color: white;
c'est modifié ! j'ai rajouté blue france et base-blue-france qui est utilisé pour les text.

2024-07-18 15:07 UTC, yvalentin requested changes
Humm, désolé, je vois le pb pour le changement avec le base-bleu-france

Dans le setting de color, je te propose de plutôt faire de type de modification:

```scss
"yellow": (
    "background-color": $base-yellow, // supprimer cette ligne
    "color-with-background": var(--text-action-high-blue-france)
    "color": $base-yellow
  ),
```
Puis de remplacer l'utilisation de la propriété "background-color" par "color"
Et dans `card.scss`: "color" par "color-with-background" pour le cas `is-inverted`

2024-07-19 09:02 UTC, ttdm commented
Yohann ayant fait la review initiale et l'essentiel de la review étant du css, je me permet de retirer en review. 

Pour info, j'ai fais un tour sur la branche de preprod et il me semble que la modif est bien appliquée partout où elle doit l'être.

2024-07-24 08:12 UTC, yvalentin requested changes
dsl, pour le changement à faire avec `background-color` pour `color`, j'ai mal exprimé l'objective de ma demande dans la première review. Ping moi, si ce n'est toujours pas claire ;-)

Normalement, si tu merge avec main, tu devrais récupérer le le lint pour le scss. Attention la CI run le lint:sass maintenant ;-)

2024-07-24 08:12 UTC, yvalentin commented on apps/web/src/assets/scss/form.scss
> +    color: map.get(map.get(setting.$colors, "red"), "color");
issue: attention, les couleurs `red` et `red-marianne` ne sont pas les même

- `red`:  fca081
- `red-marianne`: e1000f

Est-ce que c'est voulu de changer ?

2024-07-24 08:12 UTC, yvalentin commented on apps/web/src/components/track/form/TrackSiret.vue
> +  border: solid thin map.get(map.get(setting.$colors, 'blue-france'), 'color');
suggestion: pour info si tu veux accéder à `$blue-france` directement tu peux le faire avec

```scss
setting.$blue-france
```

2024-07-24 08:12 UTC, yvalentin commented on apps/web/style.md
> +2. Utilisation à travers le tableau `$colors` et de la fonction `map.get`.
praise: merci pour la mise à jour de la documentation

On peux aussi ajouter que pour utiliser le format `map.get`, il faut inclure la lib scss

```scss
@use 'sass:map';
```
Et l'ajouter dans les exemples

2024-07-25 13:42 UTC, merged