Fix: ajout de marges dans le détail des programs
betagouv/mission-transition-ecologique pull request #888
Opened 2024-07-15 15:36 UTC by oumeimaelisbihani

- ajout de fr-container dans les deux accordéons des détails du programme

2024-07-18 14:51 UTC, yvalentin requested changes
Avec le merge de `main`, je suis pas sur que le `fr-container` soit encore nécessaire... 
Et il faudrait voir pour harmonizer avec l'ensemble des accordéons (page projet,...)

Il reste aussi du padding à gauche à enlever en mode mobile pour la page de détail d'un programme

![padding-program](https://github.com/user-attachments/assets/04a5f63b-876f-4a9d-9e56-61f7fb9e874c)

2024-07-23 14:39 UTC, oumeimaelisbihani commented
Le container est bien nécessaire pour avoir la bonne marge, du coup je l'ai mis aussi pour les accordéons des descriptions des projets.

2024-07-24 08:28 UTC, yvalentin reviewed
suggestion: on pourrait aussi enlever les marges ici pour le mode mobile

![image](https://github.com/user-attachments/assets/62d95b97-cd0f-4687-a9b6-18235391b0cf)

Super pour le reste et l'harmonisation de l'ensemble des accordéons qui avait sens à avoir un `fr-container`

2024-07-25 11:55 UTC, yvalentin approved these changes

2024-07-25 11:55 UTC, yvalentin commented on apps/web/src/components/program/detail/ProgramForm.vue
> +    <div class="fr-container fr-p-0">
suggestion: la class `fr-container` ne semble dans ce cas ne pas servir, et la div aussi. Peut voir pour retirer la div ?

2024-07-25 12:31 UTC, merged