Refactor/load programs from baserow
betagouv/mission-transition-ecologique pull request #897
Opened 2024-07-18 14:53 UTC by ttdm

L'objectif de cette branche est seulement de changer la source de donnée des fichiers excels à baserow.

L'objectif est d'obtenir les fichiers yaml les plus proches possible de ce qui été généré à partir de l'excel plus des diffs issues de la mise à jour des données mais aucune différence structurelle.

De nombreux points qui questionnent ou qui semblent carrément problématique ont été relevés durant cette migration (plus d'info dans l'issue liée à la migration où dans les issues "data" ouvertes récement) mais leur traitement est en dehors du périmètre de cette PR.

2024-07-18 19:35 UTC, ttdm commented
Tous les yamls ont été revu manuellement. 
Les seuls changements publicodes sont sur : l'ordre des conditions sur les régions et des changements sur la donnée dans baserow (mise à jour des dates et réduction du nombre de thèmes ciblés )
Pour le reste des données des Yamls, il y a plus de changement, notamment à cause d'un changement de formatting des yamls. 
J'ai notamment testé que les longs strings qui comportent directement des sauts de lignes et les longues strings qui comportent des /n sont toutes deux correctement représentées. 

Sur le code je n'ai pas grand chose à dire à part qu'il y a pas mal choses non typées donc des "any" dans le code. 
C'est principalement du au fait que typer l'intégralité de la structure du yaml est complexe. 
S'il y a des "any" et des choses non typées hors de données yaml, vous pouvez me le faire remonter, ça doit être modifiable. 

Petite remarque : j'ai eu pas mal de conflits d'export de type avec la nouvelle méthode où on exporte l'intégralité des fichiers de type d'ou du naming du style "dataType".

2024-07-22 13:28 UTC, yvalentin requested changes

2024-07-22 13:28 UTC, yvalentin commented on libs/data/src/program/programYamlGenerator.ts
> +    return ['Éligible à toutes les entreprises']
suggestion: Il semblerais que retourne un `string[]`

2024-07-22 13:28 UTC, yvalentin commented on libs/data/src/program/programYamlGenerator.ts
> +    const eligibility_conditions: { [key: string]: any } = {
suggestion: il semblerais que l'on pourrait typer ici:

```ts
const eligibility_conditions: { [key: string]: string[] } = {
```

2024-07-22 13:28 UTC, yvalentin commented on libs/data/src/program/publicodesGenerator.ts
> +  constructor(private program: DataProgram) {}
suggestion: replacer `program` par `_program`

2024-07-22 13:28 UTC, yvalentin commented on libs/data/src/program/publicodesGenerator.ts
> +    const filePath = path.join(__dirname, 'publicodesStaticData.json')
question: est-ce que c'est le traitement de cas particulier ?

2024-07-22 13:28 UTC, yvalentin commented on libs/data/src/program/publicodesGenerator.ts
> +    const publicodes: any = {}
suggestion: ce n'est pas un `any` au pire c'est `{ [key: string]: any }` au mieux `{ [key: string]: unknown }`

idem pour les constantes `eligibility` et `eligibilityConditions` plus bas

2024-07-22 13:28 UTC, yvalentin commented on libs/data/src/program/publicodesGenerator.ts
> +        [Publicodes.ANY]: uniqueRegions.map((region) => `région = ${region}`).sort((a, b) => a.localeCompare(b, 'fr-FR'))
todo: Attention, besoin d'appliquer une filter avant le map car `region` peut être `null` (voir ligne 109)

2024-07-22 13:28 UTC, yvalentin commented on libs/data/src/program/publicodesGenerator.ts
> +    console.log(
suggestion: si c'est un warning autant utilisé `console.warn`

2024-07-23 08:13 UTC, ttdm commented on libs/data/src/program/publicodesGenerator.ts
> +        [Publicodes.ANY]: uniqueRegions.map((region) => `région = ${region}`).sort((a, b) => a.localeCompare(b, 'fr-FR'))
C'est volontaire de faire crash le script. j'ai modifié le console.log en console.error.

2024-07-23 08:15 UTC, ttdm commented on libs/data/src/program/publicodesGenerator.ts
> +    const publicodes: any = {}
Modifié pour publicodes. 
Pour eligibility et eligibilityConditions, typescript n'accepte pas l'assignation de champs eligibility[X] = Y avec unknown.

2024-07-23 08:20 UTC, ttdm commented on libs/data/src/program/programYamlGenerator.ts
> +  private _loadOldYamlContent(oldProgramId: string): DataProgram | null {
Comme discuté, j'ai modifié pour restreindre uniquement à l'image, seul field utilisé dans la data de l'ancien yaml.

2024-07-23 09:48 UTC, ttdm commented
Tous les changements proposés ont été effectués. 
Extend à partir de baserow était unetrès bonne idée.

Pour les imports, une nouvelle organisation a été adoptée. Elle permet de réduire énormément les exports. 

Seule précision sur cette organisation : ProgramData est bien un type du domaine et non de baserow. 
On génère les programs Yamls à partir de ProgramData et donc si on considère que c'est du baserow, on a du baserow partout. 
Globalement j'ai repris les même noms de champs pour éviter de faire du mapping supplémentaire comme je le fait pour els projets (la différence étant qu'il y a 10champs pour les projets et 150 pour les programmes) mais on pourrait faire du mapping supplémentaire si on le souhaitat.

2024-07-24 09:10 UTC, yvalentin requested changes

2024-07-24 09:10 UTC, yvalentin commented on libs/data/src/program/program.ts
> +import { ProgramAidType } from './types/export'
suggestion: après reflexion, je me disais que peut être le mot `shared` était plus parlant que `export`

Quand penses-tu ?

2024-07-24 09:10 UTC, yvalentin commented on libs/data/src/program/publicodesGenerator.ts
> +    if (this._program['Id fiche dispositif'] in staticData) return staticData[this._program['Id fiche dispositif']]
suggestion: ajouter les accolades ;-)

2024-07-24 14:12 UTC, ttdm commented on libs/data/src/program/programYamlGenerator.ts
> +    const programs = await new BaserowProgram(this.outputDirectory).getPrograms(false)
Pour l'instant non.

2024-07-24 14:19 UTC, ttdm commented on libs/data/src/common/baserow/project.ts
> +    const baserowThemes = await this._getTableData<Theme>(this._themeTableId)
Pour info, je n'ai pas pris ce changement (c'est le seul sur les 40+ remarques ;) ). 
Effectivement, getThemes est commun aux deux classes qui héritent baserow pour l'instant, project et program mais pour autant, je ne pense pas qu'il s'agit d'une fonctionnalité de propre à baserow. Si demain, on a un type de donnée vraiment différent qui n'utilise pas les thèmes alors on se retrouverait à charger les thèmes pour rien.

2024-07-25 07:28 UTC, merged