feat: add projects catalog
betagouv/mission-transition-ecologique pull request #915
Opened 2024-07-24 21:24 UTC by yvalentin

2024-07-31 15:44 UTC, dolemoine commented
Dans la continuité du boulot fait par Yohann : 

- reprise des composants du vue dsfr DsfrHeader et DsfrHeaderMenuLinks 
- utlisation du composant DsfrNavigation pour la gestion du menu dropdown
- quelques règles scss pour gérer l'affichage des boutons principaux du menu
- gestion de l'affichage mobile du menu 
- correction titre page catalogue des aides

issue: #786

2024-07-31 15:51 UTC, dolemoine commented
@oumeimaelisbihani @ttdm je la laisse en draft le temps de finir le merge avec main

2024-08-01 14:46 UTC, oumeimaelisbihani requested changes

2024-08-01 14:46 UTC, oumeimaelisbihani commented on apps/web/src/components/header/TeeDsfrHeader.vue
[praise] : nickel les deux composants TeeDsfrHeader et TeeHeader

2024-08-01 14:46 UTC, oumeimaelisbihani commented on apps/web/src/components/TeeHeader.vue
> +        text: 'cataloque des aides',
[a fixer] : petite erreur de type 'cataloque' au lieu de 'catalogue'

2024-08-02 07:41 UTC, dolemoine commented
@oumeimaelisbihani j'ai refait quelques petits ajustement notamment sur le style pour utiliser au max les classes générique custom ou du Dsfr

2024-08-08 09:57 UTC, merged