Tech : Publicode objective cleanup
betagouv/mission-transition-ecologique pull request #943
Opened 2024-08-05 14:54 UTC by oumeimaelisbihani

2024-08-06 08:51 UTC, dolemoine reviewed
praise : beau travail de refacto, c'est propre !

2024-08-06 08:51 UTC, dolemoine commented on libs/backend-ddd/src/program/infrastructure/publicodes.ts
> +  }
question: est-ce qu'on pourrait rapatrier cette const dans le types.ts ?

2024-08-06 08:51 UTC, dolemoine commented on libs/backend-ddd/src/program/infrastructure/publicodes.ts
> +const getNoPublicodeKey = (publicodeKey: string): FormattedPublicodesKeys | undefined => {
question: quel est le sens du naming "No" dans le nom de fonction `getNoPublicodeKey` ?

2024-08-06 08:51 UTC, dolemoine commented on libs/backend-ddd/src/program/infrastructure/publicodes.ts
> +}
question: est-ce qu'on pourrait rapatrier cet type dans types.ts ?

2024-08-06 08:51 UTC, dolemoine commented on libs/backend-ddd/src/program/infrastructure/publicodes.ts
> +  if (publicodeData) {
question: a priori ici `publicodeData` ne peut pas être null car l'appel à `getNoPublicodeObjective` dans `getNoPublicodeData` est déjà contraint par une vérification de la non nullité de `data` via la méthode `isObjectivePublicodeData`. Est-ce qu'il y a une autre utilisation de `getNoPublicodeObjective` qui justifie ce if ? dans le cas contraire ça permettrait d'exclure la possibilité de return null et d'avoir tjr `Objective[]` en retour de cette fonction. dis-moi ce que tu en penses

2024-08-06 08:51 UTC, dolemoine commented on libs/backend-ddd/src/program/infrastructure/publicodes.ts
> +    return conditions
suggestion: tu peux directement `return getNoPublicodeOjbective(publicodeData)` sans definir de const ici

2024-08-06 08:51 UTC, dolemoine commented on libs/backend-ddd/src/program/infrastructure/publicodes.ts
> +  switch (publicodeKey) {
suggestion: vu qu'il n'y a qu'un seul cas ici, un if suffirait

2024-08-06 08:51 UTC, dolemoine commented on libs/backend-ddd/src/program/infrastructure/publicodes.ts
> +export const convertProgramPublicodes = (program: ProgramType) => {
praise : super la gestion du remplacement du publicodes d'un program ! J'aime bien la logique

2024-08-06 10:11 UTC, oumeimaelisbihani commented on libs/backend-ddd/src/program/infrastructure/publicodes.ts
> +const getNoPublicodeKey = (publicodeKey: string): FormattedPublicodesKeys | undefined => {
c'était dans le sens qu'on modifie les clés comme 'entreprise . a un objectif ciblé' en 'objective' mais du coup j'ai modifié en getFormattedPublicodeKey qui est peut etre plus clair

2024-08-06 12:27 UTC, dolemoine approved these changes

2024-08-14 15:16 UTC, ttdm reviewed
J'ai une suggestion générale sur les programTypes. 
- ne pas toucher aux programmes type de la data et du back. 
- modifier le program type du front pour avoir exactement le type souhaité (supprimer tout entrée publicodes, pas de champ non utilisé...)
- sur le modèle de ce que tu as fait dans le fichier publicodes, écrire un nouveau fichier dans l'infra : frontConverter.ts  et créer les deux fonctions de conversion fronTodomain et domainToFront. 
- appeler au plus proche du point d'api possible, les fonctions de conversion. 

L'intéret de ce schéma c'est que ça modifie le moins de chose possible sur le back tout en permettant une structure "optimale" sur le front.

2024-08-22 14:30 UTC, ttdm commented
Perso je trouve la structure plus claire oui. 

Je trouve toujours étonnant le fait qu'il reste un élément qui s'appelle "publicodes" et des refs à publicodes dans le front (par exemple du naming qui explique que ce n'est en fait pas du publicodes) mais en tout cas ça reste de la refacto utile et bien faite pour moi :)

2024-08-28 09:21 UTC, oumeimaelisbihani commented
@ttdm c'est bon plus de mention de publicodes remplacé par filters comme ça si jamais on a besoin de rajouter d'autres trucs c'est plus simple

2024-09-04 10:10 UTC, yvalentin requested changes
Quelques petites supplémentaire
- remove `getPublicodeObjectiveByObjective` dans `theme.ts`
- Je me demande aussi si on peut peut être plutôt parler de theme pour le program du front plutôt que d'objectif (qui correspond à notre nomenclature de publicode)

2024-09-11 13:49 UTC, yvalentin requested changes

2024-09-11 13:49 UTC, yvalentin commented on libs/common/src/questionnaire/types/types.ts
> +  hasTheme = 'theme'
todo: Petit oublie, pas besoin du `has` ;-)

2024-09-11 13:49 UTC, yvalentin commented on libs/backend-ddd/src/program/infrastructure/frontConverter.ts
> +  [PublicodeObjective.UnknownYet]: Objective.UnknownYet
todo: Aucun besoin pour le moment que la porter de la constante soit en dehors de la class

```ts
class ... {
  private _publicodeToObjectiveMapping = {
    [PublicodeObjective.EnvironmentalImpact]: Objective.EnvironmentalImpact,
    [PublicodeObjective.EnergyPerformance]: Objective.EnergyPerformance,
    [PublicodeObjective.WaterConsumption]: Objective.WaterConsumption,
    [PublicodeObjective.BuildingRenovation]: Objective.BuildingRenovation,
    [PublicodeObjective.SustainableMobility]: Objective.SustainableMobility,
    [PublicodeObjective.WasteManagement]: Objective.WasteManagement,
    [PublicodeObjective.EcoDesign]: Objective.EcoDesign,
    [PublicodeObjective.TrainOrRecruit]: Objective.TrainOrRecruit,
    [PublicodeObjective.MakeSavings]: Objective.MakeSavings,
    [PublicodeObjective.DurablyInvest]: Objective.DurablyInvest,
    [PublicodeObjective.UnknownYet]: Objective.UnknownYet
  }
...
}
```

2024-09-11 13:49 UTC, yvalentin commented on apps/web/src/components/program/detail/ProgramDetail.vue
> +            <ProgramTheme
todo: Attention, ici c'est bien un programObjective (qui d'ailleurs existe toujours alors que ProgramTheme n'existe pas ;-) )

2024-09-11 13:49 UTC, yvalentin commented on libs/backend-ddd/src/program/infrastructure/frontConverter.ts
> +  [PublicodeObjective.EnvironmentalImpact]: Objective.EnvironmentalImpact,
todo: arff, je suis passer à côté lors de ma première review, dsl !

Il semblerais que ici on souhaite du coup plutot utilisé les themes et non plus les `Objective`

```ts
[PublicodeObjective.EnvironmentalImpact]: ThemeId.Environmental,
```

2024-09-11 13:49 UTC, yvalentin commented on apps/web/src/components/questionnaire/result/list/ThemeFiltersAndCard.vue
> +          <ThemeFilter :theme="theme as Objective" />
todo: (voir retour plus bas) -> du coup ici on aura plus 

```html
<ThemeFilter :theme="theme as ThemeId" />
```

2024-09-11 13:49 UTC, yvalentin commented on apps/web/src/components/theme/ThemeFilter.vue
> +  theme?: Objective | ''
todo: (voir retour plus bas) -> du coup ici on aura plutôt un `ThemeId`

2024-09-11 13:49 UTC, yvalentin commented on apps/web/src/questionnaire/trackBuildingProperty.ts
> +  theme: Objective.BuildingRenovation,
todo: (voir retour plus bas) -> du coup ici on aura plutôt des `ThemeId`

2024-09-11 13:49 UTC, yvalentin commented on apps/web/src/utils/theme.ts
> +  static getThemeByValue(value: Objective) {
todo: Normalement dans la def des theme, il doit être possible de supprimer la `value` et se baser sur le `id`

2024-09-16 13:29 UTC, yvalentin approved these changes
Praise: Trop cool ! Gros boulot de refacto !!

(J'ai pas trouvé comment d'embêter un peu plus ^^)

2024-09-16 13:29 UTC, yvalentin commented on apps/web/src/components/questionnaire/result/list/ResultList.vue
> +    : (UsedTrack.getPriorityTheme() ?? '')
Praise: Bien vu la simplification

2024-09-16 13:38 UTC, merged