Feature : Ajout de liens directs vers les projets sur les cartes Thématiques du parcours 'j'ai un projet en tete'
betagouv/mission-transition-ecologique pull request #947
Opened 2024-08-07 14:12 UTC by oumeimaelisbihani

Utilisation du même composant ProjectButton pour les projets liés (détails d'un projet) et les cartes thématiques

2024-08-07 14:46 UTC, dolemoine approved these changes

2024-09-06 09:02 UTC, dolemoine requested changes
Praise: chouette intégration des projets mis en avant cliquable !

todo: en terme fonctionnel, peut-être qu'il faudrait modifier le curseur au hover sur l'ensemble de la card, car on a l'impression que toute la card est cliquable.

2024-09-23 13:46 UTC, dolemoine approved these changes

2024-09-25 15:53 UTC, yvalentin requested changes
Praise: super pour la navigation. On peux pas ouvrir les cartes dans un nouvelle onglet mais on on verra plus tard si besoin !

Deux point:
 - ul/li
```
<div class="fr-card__desc">
          <ul class="fr-tags-group">
            <TeeProjectButton
              v-for="project in option.highlightProjects"
              :key="project.id"
              class="highlighted-project fr-mx-1v fr-my-1v inline-flex"
              :color="option.color"
              size="sm"
              :project="project"
            />
            <span
              v-if="option.moreThanThree"
              class="fr-m-auto fr-ml-0"
              >...</span
            >
          </ul>
        </div>
```
Ici si on utilise un `ul`, il doit y avoir un `li`, de plus avec le `fr-tags-group`, il manque l'utilisation de `fr-tag` (et donc le css doit être adapté.

- css/scss
Avec la class `theme-card` sur la balise contenant `fr-card`. Il doit être possiblie de tout passer en utilisant uniquement les class dsfr et de les surcharger avec nos besoin...

ex
```scss
.fr-card {
  &.theme-card {
     .fr-card__body {
...
````

2024-09-25 15:53 UTC, yvalentin commented on apps/web/src/components/theme/select/ThemeSelect.vue
> +      @keydown.enter="selectOption(opt.value)"
praise : :+1:

2024-10-02 12:40 UTC, yvalentin commented on apps/web/src/components/theme/select/ThemeCard.vue
> +          >
question: Tu as choisi de finalement enlever le `<ul>`... Quel est la raison ?

2024-10-02 12:44 UTC, yvalentin commented on apps/web/src/components/theme/select/ThemeCard.vue
>  .theme-card:active,
suggestion: cette partie de hover et active semble pouvoir se retrouver aussi dans la `card.scss`

2024-10-02 12:49 UTC, yvalentin commented on apps/web/src/components/theme/select/ThemeCard.vue
>  .theme-card:active,
suggestion: il est possible de faire de `scss` dans les fichiers `.vue`

```scss
<style scoped lang="scss">
.theme-divider {
  height: 4px;
  width: 15%;
}

.highlighted-project {
  max-width: 90%;

  &:active {
    box-shadow: 1px 2px 8px 2px rgb(0 0 0 / 10%);
  }
}
</style>
```

2024-10-02 15:05 UTC, merged