Feat: front end testing
betagouv/mission-transition-ecologique pull request #976
Opened 2024-08-19 16:12 UTC by ttdm

Adding playwright to the project. 

Draft PR at the moment, testing the CI.

2024-09-04 13:54 UTC, yvalentin requested changes
- le dossier web-e2e doit pouvoir être ajouter à l'architecture `nx`

- voir la possibilité/interet de passer par publicode evaluation pour tester nos resulats sur le front en e2e (et voir si ça remplace le concept de comparaison entre prod et CI ou s'ajoute)

2024-09-04 13:54 UTC, yvalentin commented on apps/web/src/components/project/list/ProjectCard.vue
> +    class="playwright-project-target"
suggestion: remplacer la class `playwright-project-target` par `project-card`

2024-09-04 13:54 UTC, yvalentin commented on apps/web-e2e/projectResults.spec.ts
> +      // it also happen in some other tests cases where there are elements for an unknown reason
suggestion: amélioration des errors, par exemple avoir des message plus explicite. Exemple le cas où le selecteur n'est pas trouvé...

2024-09-04 13:54 UTC, yvalentin commented on playwright.config.ts
> +import { defineConfig, devices } from '@playwright/test'
suggestion: il semble possible de mettre ce fichier dans le dossier web-e2e. Avec l'ajout d'un option à la command

```cmd
npx playwright test --config ./app/web-e2e/playwright.config.ts

2024-09-04 13:54 UTC, yvalentin commented on apps/web-e2e/programResults.spec.ts
> +const testUrl = 'http://localhost:4242/'
suggestion: possibilité de mettre des variables de config dans un global setup

https://playwright.dev/docs/test-global-setup-teardown#example

2024-09-23 14:19 UTC, ttdm commented on apps/web-e2e/projectResults.spec.ts
> +      // it also happen in some other tests cases where there are elements for an unknown reason
comme discuté, c'est attendu pour certains browsers d'où le message.

2024-09-30 17:14 UTC, ttdm commented on apps/web/src/components/project/list/ProjectCard.vue
> +    class="playwright-project-target"
C'est intéressant de voir que pour les programmes, le fr-mb-2v a sauté ! 

J'y ai ajouté : teste2e-program-target.
J'ai vraiment l'impression que c'est nécessaire de bien mettre un nom qui indique la finalité pour que ce ne soit pas modifié.

2024-09-30 18:25 UTC, ttdm commented on apps/web-e2e/programResults.spec.ts
> +const testUrl = 'http://localhost:4242/'
La gestion du global setup et des workers a l'air un peu complexe (par défaut il n'est pas dispo dans les workers). 

Je suis passé par l'argument BaseURL du fichier de config.

2024-10-02 15:09 UTC, yvalentin commented on apps/web-e2e/src/programResults.spec.ts
> +  test(`Verify programs number and order for query number ${singleTest.id}`, async ({ page }) => {
question: Est-e que l'on peux mettre la query qui est effectué dans le nom du test ? Ca permettrais de voir plus facilement l'url qui plante... (Est-ce que ça a du sens pour toi ?)

2024-10-02 15:36 UTC, ttdm commented on apps/web-e2e/src/programResults.spec.ts
> +  test(`Verify programs number and order for query number ${singleTest.id}`, async ({ page }) => {
jsuis pas sur que ce soittrès lisible mais je peux tenter :)

2024-10-02 17:03 UTC, merged