Feat: update opportunity status on transmission
betagouv/mission-transition-ecologique pull request #991
Opened 2024-08-23 09:37 UTC by ttdm

La PR est fonctionnelle mais je ne suis pas super fan de son archi. 

L'idée est de modifier le statut sur brevo au lieu de la colonne envoyée (puis à terme de cacher la colonne envoyée sur le site Brevo).

"Problème" : le statut correspond à une ID dépendant de l'ID de la pipeline brevo.
Je considère que cet id n'est pas une donnée sensible et je l'ai donc hard codé. 
La solution proposée permet de ne pas dévoiler l'id de la pipeline de prod.

La solution proposé cassera si on modifie les pipeline utilisées sur brevo.
La seule solution pour que ce ne soit pas le cas serait de query brevo pour obtenir dynamiquement l'id mais ça augmente le nombre d'appel à des services externe et donc le temps des transaction ce qui ne me plait pas. 

Point annexes de la PR: 
- fix du script de récup des données avec l'ajout de la valeur "EI"
- fix de la méthode "reachedDailyTransmissionLimit" pour PDE avec l'ajout de la prise en compte des projets !

2024-08-26 12:26 UTC, yvalentin requested changes
Quelques petits retours


Sinon, voir aussi le ticket suivant

https://github.com/orgs/betagouv/projects/54/views/3?pane=issue&itemId=76365434

2024-08-26 12:26 UTC, yvalentin commented on libs/backend-ddd/src/opportunity/infrastructure/api/brevo/types.ts
> +export enum BrevoStatus {
suggestion: `BrevoDealStatus` ?

2024-08-26 12:26 UTC, yvalentin commented on libs/backend-ddd/src/opportunity/infrastructure/api/brevo/types.ts
> +  deal_stage?: string
suggestion: `dealStage` semble pouvoir être un valeur de l'enum ?
```suggestion
  deal_stage?: BrevoStatus
```

2024-08-26 12:26 UTC, yvalentin commented on libs/backend-ddd/src/opportunity/infrastructure/api/brevo/brevoDeal.ts
> +    }
suggestion: peut être plus simple ?

```suggestion
    return {
      envoy: domainUpdateAttributes.sentToOpportunityHub,
      deal_stage: Config.BREVO_DEAL_PIPELINE == '65ce1a5e59d96ff2630f06c8' ? BrevoStatus.TestTransmitted : BrevoStatus.Transmitted
    }
```

2024-09-04 09:03 UTC, ttdm commented on libs/backend-ddd/src/opportunityHub/infrastructure/api/placedesentreprises/placeDesEntreprises.ts
> +      if (prevProgram === undefined) {
Je l'ai "fait" mais pour info, c'est pas la même donnée. Dans opportunity features on est sur un id : number alors que la on est sur le slug.
j'ai fait une proposition qui débute un ddd de projet mais qui n'est pour l'isntant pas réellement un ddd (pas d'interface). 
ça me semble être le plus simple : clair et fonctionnel pour l'instant. 
Je ne sais pas ce que tu en penses.

2024-09-04 09:27 UTC, yvalentin approved these changes

2024-09-05 06:38 UTC, merged